### ISSUE TITLE
아이템 11. EQUALS를 재정의하려거든 HASHCODE도 재정의하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#11]

**Comment by gaepury** [comment]
### equals를 재정의한 클래스 모두에서 hashCode도 재정의해야 한다.
> 그렇지 않으면 hashCode(Object)의 일반 규약을 어기게 되므로, HashMap, HashSet, HashTale 같은 해시 기반 컬렉션과 함께 사용하면 오동작한다

> 아래는 Object 명세에서 발췌한 hashCode 관련 규약이다.

>> 1. equals 비교에 사용되는 정보가 변경되지 않았다면, 애플리케이션이 실행되는 동안 그 객체의 hashCode 메서드는 몇 번을 호출해도 일관되게 항상 같은 값을 반환해야 한다. 단, 애플리케이션을 다시 실행한다면 이 값이 달라져도 상관없다.
>> 2. equals(Object)가 두 객체를 같다고 판단했다면, 두 객체의 hashCode는 똑같은 값을 반환해야 한다.
>> 3. equals(Object)가 두 객체를 다르다고 판단했더라도, 두 객체의 hashCode가 서로 다른 값을 반환할 필요는 없다. 단, 다른 객체에 대해서는 다른 값을 반환해야 해시테이블의 성능이 좋아진다.

따라서 equals를 재정의한 클래스 모두에서 hashCode도 재정의해야 한다.

## 문제 상황
![image](https://user-images.githubusercontent.com/20143765/49623888-cd913100-fa12-11e8-9d97-9abe7b76fde6.png)

```java
Map<PhoneNumber, String> m = new HashMap<>();
m.put(new PhoneNumber(707, 867, 5309), "Jenny");
m.get(new PhoneNumber(707, 867, 5309)); // null 반환
```
이 문제는 PhoneNumer에 적절한 hashCode 메서드를 작성해주면 해결

## hashCode 메서드 작성
- equals(Object) 메서드 호출 결과가 false인 두 객체들의 hashCode값이 최대한 다르게 나오도록 hashCode 메서드를 오버라이드 해야한다.
- 구현후 동치인 인스턴스에 대해 똑같은 해시코드를 반환하는지 단위 테스트가 필요

### 1. 전형적인 hashCode 메서드
   1. int변수 result를 선언한 후 값 c로 초기화. c는 해당객체의 첫번째 핵심필드를 아래 2의 방식으로 계산한 해시코드.
   2. 각 필드에 대해 아래와 같이 hash code값을 구한다.
      - 기본 타입 필드라면 Type.hashCode(f)을 수행. 여기서 Type은 해당 기본타입의 박싱 클래스
          - Short, Integer 등
      - 참조형이면, 객체의 hashCode 메서드 호출(null이면 0, 다른 상수도 괜찮은데 전통적으로 0을 사용한다고 한다..)
      - 필드가 배열이라면 Arrays.hashCode를 사용
          - 배열내 모든 원소가 핵심원소일때..
          - 아니라면 핵심원소 각각을 별도 필드처럼 다뤄서 위처럼 hash code를 구한다
   3. 2에서 계산한 해시코드로 result 갱신
      - result=31 * result + 계산한 해시코드
      - 필드를 곱하는 순서에 따라 result값이 달라지게 한다..
         - String의 hashCode를 곱셈 없이 구현한다면 구성하는 철자가 같고 그 순서만 다른 문자열의 해쉬코드가 같아진다.. 어렵다..
            - ![image](https://user-images.githubusercontent.com/20143765/49626619-13072b80-fa1e-11e8-99d7-e872a5a1fc1e.png)
      - 31을 곱하는 이유?
         - 홀수이면서 소수이다.
             - 만약 이 숫자가 짝수이고 오버플로우 발생시 정보를 잃게된다. => 예상한 해쉬값 반환이 안된다.
                - 홀수이면 오버플로우 발생시 정보를 안잃나? 짝수일경우에는 곱해지는 과정에서 비트가 0으로 다 세팅되는 이슈가 생길수 있음. 홀수일경우 그런 이슈가 없다.
         - https://code.i-harness.com/ko-kr/q/49128
   4. result 반환
```java
    @Override public int hashCode() {
        int result = Short.hashCode(areaCode);
        result = 31 * result + Short.hashCode(prefix);
        result = 31 * result + Short.hashCode(lineNum);
        return result;
    }
```
- 단순하고 충분히 빠르고 품질면에서나 해싱 기능 면에서나 자바 플랫폼 라이브러리가 사용한 방식과 견줄만함
   - 해시 충돌을 더더 적은 방법을 굳이 사용하고 싶다면?
      - 구글 개발자 답게 구아바의 com.google.common.hash.Hasing을 추천
      - 해시 충돌 관련 글 : https://d2.naver.com/helloworld/831311 (Naver D2)

### 2. 한줄짜리 hasoCode 메서드 
- Objects 클래스의 hash 정적 메소드를 이용
   - 임의의 개수만큼 객체를 받아 해시코드를 계산해줌
- 성능이 살짝 아쉽다.
   - why? 입력 인수를 담기 위한 배열이 만들어지고 입력중 기본타입이 있다면 박싱과 언박싱도 거챠야 하기 때문.
```java
   @Override public int hashCode() {
        return Objects.hash(lineNum, prefix, areaCode);
    }
```
### 3. 해시코드를 지연 초기화(lazy initialization)하는 hashCode메서드
- 해쉬코드 생성비용이 너무 비쌀 경우 지연초기화를 통해 캐쉬처리하면 유용
- 스레드 안정성까지 고려해야한다.
   - 아이템3에서 소개했던 lazy initialization에 의한 스레드 문제..와 같다
```java
    priate int hashCode; //자동으로 0으로 초기화된다.
    @Override public int hashCode() {
        int result = hashCode;
        if (result == 0) {
            result = Short.hashCode(areaCode);
            result = 31 * result + Short.hashCode(prefix);
            result = 31 * result + Short.hashCode(lineNum);
            hashCode = result;
        }
        return result;
    }
```
### 4. HashCodeBuilder나 @EqualsAndHashCode(실무에서 쓰일수 있는 유용한 방법)
- HashCodeBuilder (apache)
   - Docs : https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/builder/HashCodeBuilder.html
```
public int hashCode() { return HashCodeBuilder.reflectionHashCode(this); }
```
- @EqualsAndHashCode
   - Docs : https://projectlombok.org/features/EqualsAndHashCode
   - 클래스에 @EqualsAndHashCode 어노테이션만 추가
      - 이름자체에서부터 같이 재정의하라고 나타내준다.. Good
![image](https://user-images.githubusercontent.com/20143765/49626001-3b415b00-fa1b-11e8-8138-e7f2ec55fe73.png)
   

### 주의사항
- 성능을 높인답시고 해시코드를 계산할 때 핵심 필드를 생략해서는 안된다.
   - 속도야 빨라지겠지만 해시테이블의 성능을 심각하게 떨어뜨릴 수도 있다.
- equals 비교에 사용되지 않은 필드는 hashCode 에서도 반드시 제외해야한다.
- hashCode 반환 값의 생성 규칙을 사용자에게 알리지 말아라
   - 사용하는 개발자가 이 값에 의지하고 코드에 반영해버리면 문제가 생길 수 있다.(추후 계산방식을 바꿀때 문제가 될수있다)
