### ISSUE TITLE
아이템 12. TOSTRING을 항상 재정의하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#12]

**Comment by nypark425** [comment]
### ```Object.toSring()```란?
```java
public String toString() {
    // 단순히 "클래스명+@+16진수 해시코드"를 반환합니다.
    return getClass().getName() + "@" + Integer.toHexString(hashCode());
}
```

### ```toString()```이 강조하는 것?
- ```Object.toString()```에는 이렇게 써있습니다.
> In general, the toString method returns a string that "textually represents" this object.
> 일반적으로, ```toString```메소드는 해당 object를 "그대로 표현하는" string을 반환한다.

> It is recommended that all subclasses override this method.
> 모든 하위 클래스는 이 메소드를 override하길 추천한다!

### 기사를 피딩하는 시스템을 만들어보자.
```java
public class Article {
    private String officeId;
    private String articleId;
    private String crc32;

    public Article(String officeId, String articleId, String crc32) {
        this.officeId = officeId;
        this.articleId = articleId;
        this.crc32 = crc32;
    }
    // getter, setter 생략
```
```java
public static void main(String[] args) {
    FeedingSystem feedingSystem = new FeedingSystem();
    Article article = new Article("001", "1234567890", "yn12345");
    try {
        feedingSystem.feed(article);
    } catch (Exception e) {
        // 어떤 기사에서 에러가 났는지 확인해야하니까 한번 출력해봅시다.
        System.out.println("피딩에 실패했습니다.: " + article);
    }
}
```
- ```feedingSystem.feed(article)```에서 에러가 발생한다면?
    - ```Object.toString()```을 사용하므로 아래처럼 출력될 겁니다. 그런데... 저게 어떤 기사지?
```
기사를 피딩합니다...
피딩에 실패했습니다.: nypark.study.effectivejava3.chapter3.item12.Article@3cd1a2f1
```

### ```toString()```을 재정의해보자.
```java
public class Article {
    // 생략
    @Override
    public String toString() {
        return getClass().getName() + 
                "\nofficeId: " + officeId + 
                "\narticleId: " + articleId + 
                "\ncrc32: " + crc32;
    }
}
```
- 에러가 나도 어떤 기사인지 알겠네요.
```
기사를 피딩합니다...
피딩에 실패했습니다.: nypark.study.effectivejava3.chapter3.item12.Article
officeId: 001
articleId: 1234567890
crc32: yn12345
```
> ```toString()```을 잘 구현한다면, 그 클래스는 사용하기에 즐거워지고, 그 클래스를 사용한 시스템은 디버깅하기 쉬워집니다.
> 이왕이면 객체가 가진 주요 정보 모두를 반환한다면 가장 베스트지만, 객체가 너무 거대하거나 string으로 객체를 표현하기 적합하지 않다면 정말 핵심정보만이라도 반환한다면 좋을 것 같네요.

### ```toString()```은 내 마음대로 정의하면 되나?
- ```toString()```이 반환하는 값의 포맷을 문서화할지 고민은 필요합니다.
- 포맷을 정해버리면?
    - 표준적이며, 명시적이고, 사람이 읽을 수 있는 객체가 됩니다.
```java
/**
 * 이 기사의 문자열로 된 정보를 반환한다.
 * 언론사 id는 3자리의 숫자로 표현된 문자열,
 * 기사 id는 10자리의 숫자로 표현된 문자열,
 * crc32는 자유로운 형식의 문자열이다.
 */
@Override
public String toString() {
    return String.format("%03d-%010d-%s",
            Integer.parseInt(officeId),
            Integer.parseInt(articleId),
            crc32);
}
```
- 하지만 장점만 있는 것은 아닙니다. 그 포맷에 계속 얽매이게 되기 때문입니다.
    - 향후를 위해 유연성있게 가는 것도 좋겠네요.
```java
/**
 * 이 기사의 문자열로 된 정보를 반환한다.
 * 다음은 일반적인 형태이나, 정해진 것은 아니며 향후 변경될 수 있다.
 * 
 * "officeId: {언론사Id}
 * articleId: {기사Id}
 * crc32:     {기사의 crc32}"    
 */
@Override
public String toString() {
    return getClass().getName() + 
            "\nofficeId: " + officeId + 
            "\narticleId: " + articleId + 
            "\ncrc32: " + crc32;
}
```

### ```toString()```에서 얻을 수 있는 정보라면, API를 제공하자.
- 사용자가 ```toString()```을 파싱하는 일이 없도록, getter 등 접근할 수 있는 메소드를 제공합시다.

**Comment by enochyeon** [comment]
최근엔 ToStringBuilder.reflectionToString()을 많이 사용하네요.

**Comment by seryang** [comment]
<ToStringBuilder 참고 자료>
* https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/builder/ToStringBuilder.html
* https://jdm.kr/blog/227
