### ISSUE TITLE
아이템 13. CLONE 재정의는 주의해서 진행하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#13]

**Comment by enochyeon** [comment]
# Cloneable

## 소스 코드
```java
package java.lang;

public interface Cloneable {
  // 아무것도 없음
}
```

## 소개
* 복제해도 되는 클래스임을 명시하는 용도의 mixin interface(#20)
* Object의 clone 동작방식 결정
* 널리 쓰이기 때문에 잘 알아둘 필요 있음

## 문제
* clone 메서드가 Object에 **protected** 로 선언되어 있음
  * 외부에서 호출할 수 없음.
  * 리플렉션(#65)하면 사용할 수도 있지만 100% 제공 보장은 안됨
* 일반적으로 인터페이스를 구현하는 것은 미리 정의된 기능을 제공하는 것이지만, Cloneable은 **상위 클래스에 정의된** clone의 동작 방식을 변경한다.
* 자신을 비롯한 모든 상위 클래스가 잘 지켰을 때만 제대로된 복사본을 제공할 수 있음
  * (참고) 복사의 일반적인 의도
    * [참] x.clone() != x
    * [참] x.clone().getClass() == x.getClass() (필수 아님)
    * [참] x.clone().equals(x)  (필수 아님)
* clone 메소드를 조작하는 경우 하위 클래스에서 의도하지 않은 결과를 받을 수 있음

---

# 사용하기

## 기본적인 복사

#### 코드 13-1 가변 상태를 참조하지 않는 클래스용 clone 메서드(#10 PhoneNumber)
```java
@Override public PhoneNumber clone() {
  try {
    return (PhoneNumber) super.clone(); // <--- 타입 변환
  } catch {CloneNotSupportedException e) {
    throw new AssertonError(); // 일어날 수 없는 일이다.
  }
}
```

* 공변 반환 타이핑(covariant return typing)
* 상위의 하위 타입으로 변환했기 때문에 문제 없음
* CloneNotSupportedException이 unchecked exception인게 좋겠음(#71)

## 가변객체 복사하기 1 - 재귀호출

* Stack 클래스(#7)
  * https://github.com/WegraLee/effective-java-3e-source-code/blob/master/src/effectivejava/chapter3/item13/Stack.java
* super.clone()을 그대로 사용하는 경우, shallow copy가 되는 문제 발생

#### 코드 13-2 가변 상태를 참조하는 클래스용 clone 메서드
```java
@Override public Stack clone() {
    try {
        Stack result = (Stack) super.clone();
        result.elements = elements.clone(); // <--- 배열은 clone 기능을 제대로 사용함
        return result;
    } catch (CloneNotSupportedException e) {
        throw new AssertionError();
    }
}
```

* clone 재귀호출로 해결
  * 배열은 clone을 제대로 사용하고 있음
* 필드가 final이 아니었기 때문에 재할당 할 수 있었음.
* Cloneable 아키텍처는 '가변 객체를 참조하는 필드는 final로 선언하라'는 일반 용법과 충돌.
* 때에 따라 final을 제거해야 할 수도 있음.

## 가변객체 복사하기 2 - 깊은 복사

#### 경량 해시테이블
```java
public class HashTable implements Cloneable {
  private Entry[] buckets ...;

  private static class Entry {
    final Object key;
    Object value;
    Entry next;

    Entry(Obejct key, Object value, Entry next) {
      this.key = key;
      this.value = value;
      this.next = next;
    }
  }
  ... // 이하 생략
}
```

#### 코드 13-3 잘못된 clone 메서드 - 가변 상태를 공유한다!
```java
@Override public Stack clone() {
    try {
        HashTable result = (HashTable) super.clone();
        result.buckets = buckets.clone(); // <---
        return result;
    } catch (CloneNotSupportedException e) {
        throw new AssertionError();
    }
}
```
* 원본과 동일한 연결 리스트를 참조하게 됨

#### 코드 13-4 복잡한 가변 상태를 갖는 클래스용 재귀적 clone 메서드
```java
// 클래스에 새로운 메서드 추가
Entry deepCopy() {
  return new Entry(key, value, next == null ? null : next.deepCopy()); // <---
}
```
```java
@Override public Stack clone() {
  try {
    HashTable result = (HashTable) super.clone();
    result.buckets = new Entry[buckets.length]; // <---
    for (int i = 0 ; i < buckets.length ; i++) { // <--- 개선
      if (buckets[i] != null) {
        result.buckets[i] = bueckets[i].deepCopy(); // <---
      }
    }
    return result;
  } catch (CloneNotSupportedException e) {
    throw new AssertionError();
  }
}
```
* 리스트가 길어지면 스택 오버플로를 일으킬 위험 있음

#### 코드 13-5 엔트리 자신이 가리키는 연결 리스트를 반복적으로 복사한다
```java
Entry deepCopy() {
  Entry result = new Entry(key, value, next);
  for (Entry p = result ; p.next != null ; p = p.next) { // <--- 재귀에서 반복으로 개선
    p.next = new Entry(p.next.key, p.next.value, p.next.next);
  }
  return result;
}
```

## 가변객체 복사하기 3 - 고수준 메서드 사용

* 모든 필드를 초기화 하고 원본의 필드를 건건이 복사하는 메소드를 만드는 것
* 속도가 느릴 수 있음
* Cloneable 아키텍쳐와는 어울리지 않는 방식
* 하위 메서드에서 재정의 되지 않도록 해야함
  * 생성자에서는 재정의될 수 있는 메서드를 호출하지 않아야 하는 것(#19)과 비슷
* throws 절을 없애. 검사 예외를 던지지 않아야 그 메서드를 사용하기 편하기 때문(#71)
* 상속용 클래스는 Cloneable 구현하지 않기. 상속해서 쓰기 위한 클래스 설계 방식(#19) 참고

#### 코드 13-6 하위 클래스에서 Cloneable을 지원하지 못하게 하는 clone 메서드
```java
protected final Object clone() throws CloneNotSupportedException { // <--- final 붙임
  throw new CloneNotSupportedException();
}
```

## 안전하게 사용하기 - 동기화 처리

* 스레드 안전 클래스를 작성할 때는 clone 메서드도 적절히 동기화해야 한다.(#78)
* Cloneable을 구현하는 모든 클래스는 clone 재정의 필요
  * public
  * 반환 타입은 클래스 자신
  * 일련번호, 고유ID 등은 수정해주기

---

# 더 나은 방향

* Cloneable을 굳이 복잡하게 사용할 필요가 없으니 다른 방식으로 하자
* 복사 생성자 >> 변환 생성자(conversion constructor)
* 복사 팩터리 >> 변환 팩터리(conversion factory)

#### 코드 13-7 복사 생성자
```java
public Yum(Yum yum) { ... };
```

#### 코드 13-8 복사 팩터리
* 복사 생성자를 모방한 정적 팩터리(#1)
```java
public static Yum newInstance(Yum yum) { ... };
```
