### ISSUE TITLE
아이템 19. 상속을 고려해 설계하고 문서화하라. 그러지 않았다면 상속을 금지하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#19]

**Comment by gaepury** [comment]
## 문서화
### 상속용 클래스는 재정의할 수 있는 메서드들을 내부적으로 어떻게 이용하는지(자기사용) 문서로 남겨야 한다.
   - 오버라이드 가능한 메서드에 관한 모든것을 문서화해야 한다고 생각하면 된다.

>> 클래스의 API로 공개된 메서드에서 클래스 자신의 또다른 메서드를 호출할 수도 있다. 그런데 마침 호출되는 메서드가 재정의 가능 메서드라면 그 사실을 호출하는 메서드의 API 설명에 적시해야 한다. 덧붙여서 어떤 순서로 호출하는지, 각각의 호출결과가 이어지는 처리에 어떤 영향을 주는지도 담아야 한다.
    - 재정의 가능 메서드 : pulbic과 protected 메서드 중 final이 아닌 모든 메서드

<br/>

- 문서화 내용에는 아래와 같은 내용들이 들어가야 한다.
   - "This implements(현재 구현 버전)"이라는 구문으로 시작
   - 메서드 내부에서 처리하는 작업에 대한 설명
     ![image](https://user-images.githubusercontent.com/20143765/50972113-144ddb80-1529-11e9-97ca-6e1fd121a6be.png)
      - 이 설명에 따르면 iterator 메서드를 재정의하면 remove 메서드의 동작에 영향을 줌을 확실히 알 수 있다.
      - 사실 메서드를 이용하는 입장에서는 메서드가 무슨(What) 일을 하는지가 중요하지, 어떻게(How) 일을 하는지는 중요하지 않다. 하지만 상속 관계에서 서브 클래스가 안전하게 오버라이드  할 수 있게 문서화를 하려면, 어떻게(How) 일을 하는지 기술해야 한다.

## 설계
### 상속을 위한 설계 시 몇가지 주의할 점들
1. 클래스 설계 시 어떤 protect메서드나 필드를 제공해야 하는지 심사 숙고해서 생각하자.
   - 유지보수 측면에서 protected 메서드나 필드를 최소화해야 하지만, 아예 없으면 사실상 상속의 의미가 없게 된다.
   - 상속용 클래스를 시험하는 방법은 직접 하위 클래스를 만들어보는 것이 유일하다.( 꼭 필요한 protected 멤버를 놓쳤다면 하위 클래스를 작성할 때 그 빈자리가 확연이 드러난다.)
      - 하위클래스를 여러개 만들때까지 전혀 쓰이지 않는 protected멤버는 사실 private이었어야 할 가능성이 크다.

2. 상속용 클래스의 생성자는 직접적으로든 간접적으로든 재정의 가능 메서드를 호출해서는 안된다.
   - 이 규칙을 어기면 오동작 유발
#### 예제
```java
public final class Sub extends Super {
    // Blank final, set by constructor
    private final Instant instant;

    Sub() {
        instant = Instant.now();
    }

    // Overriding method invoked by superclass constructor
    @Override public void overrideMe() {
        System.out.println(instant);
    }

    public static void main(String[] args) {
        Sub sub = new Sub();
        sub.overrideMe();
    }
}
```
```java
// Class whose constructor invokes an overridable method. NEVER DO THIS! (Page 95)
public class Super {
    // Broken - constructor invokes an overridable method
    public Super() {
        overrideMe();
    }

    public void overrideMe() {
    }
}
```
   - 결과 : ![image](https://user-images.githubusercontent.com/20143765/50975478-1156e900-1531-11e9-8bae-6b85870153d5.png)
   - private, final, static 메서드는 재정의가 불가능하지 생성자에서 안심하고 호출해도 된다.


### 클래스를 상속용으로 설계하려면 엄청난 노력이 들고 제약도 상당하다는 것을 명심하자!!

### 상속 금지 방법
- 클래스를 final로 선언
- 모든 생성자를 private로 선언하고, 생성자 대신 public static 팩토리 메서드를 구현
   - 핵심 기능을 정의한 인터페이스가 있고, 클래스가 그 인터페이스를 구현했다면 상속을 금지해도 개발하는데 아무런 어려움이 없다. #18(아이템18)에서 설명한 래퍼클래스 패턴 역시 기능을 증강할 때 상속대신 쓸수 있는 더 나은 대안.
