### ISSUE TITLE
아이템 20. 추상 클래스보다는 인터페이스를 우선하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#20]

**Comment by nypark425** [comment]
### 인터페이스와 추상클래스
> 자바 8 > 인터페이스에 ```default method```가 추가되었습니다. (#21) [(oracle docs)](https://docs.oracle.com/javase/tutorial/java/IandI/defaultmethods.html)
> 인터페이스에서도 메소드를 정의할 수 있게 되었습니다.
```java
public interface LivingThings {
    void eat();
    void sleep();
    default void walk() {
        System.out.println("I'm walking!");
    }
}
```
> 자바 8 이전에 쓰여진 인터페이스들의 자유로운 확장이 가능해졌습니다.
> default 메소드를 사용하면 그 인터페이스를 구현한 클래스에서는 override할 필요가 없기 때문입니다.

- ```default method```도 생겼는데, 그럼 인터페이스와 추상클래스는 어떤 차이가 있는 걸까요?
    - 여전히 큰 차이가 있습니다.
    - 추상클래스를 상속한 클래스는 추상클래스의 하위 클래스가 됩니다.
        - 단일 상속만 지원하는 자바에서 추상클래스를 상속한 채로 새로운 타입을 정의하기엔 어렵습니다.
    - 인터페이스를 올바르게 구현한 클래스는, 같은 타입으로 취급됩니다. (다형성)

### 추상클래스에 비해 자유로운 인터페이스
- 기존 클래스들에 추상클래스를 상속하고 싶다면, 계층 구조에 큰 혼란을 야기할 수 있습니다.
    - A, B 클래스에 동일한 추상클래스를 상속하려고 한다면, 계층 구조상 공통 조상인지 고민해야합니다.
    - 클래스 C가 추상클래스를 상속하게 되면 C의 모든 자손들도 강제로 상속하게 되므로 고민해야합니다.
- 하지만 기존 클래스에 인터페이스를 구현하고 싶다면, 요구 메소드를 추가하고 ```implements```만 추가하면 됩니다.

### 인터페이스는 믹스인(mixin) 정의에 안성맞춤!
> 믹스인(mixin) : '대상 클래스의 주된 기능에 선택적 기능을 혼합(mixed in)한다'
```java
package java.io;
public class File implements Serializable, Comparable<File> {
    // 필드 및 메소드 생략
}
```
- ```File```클래스가 ```Comparable```를 구현했다는 건?
    - ```File``` 클래스의 인스터스끼리는 *순서를 정할 수 있다*는 것을 의미합니다.
- 추상클래스는 왜 믹스인이 불가능할까요?
    - 추상클래스는 기존 클래스에 덧씌우기 어렵고, 여러 부모를 섬길 수 없는 '클래스 계층구조'에는 믹스인을 사용하기에 합리적인 위치가 없기 때문입니다.

### 인터페이스는 계층구조가 없는 타입 프레임워크를 만들 수 있다.
```java
public interface Singer { // 가수
    AudioClip sing(Song s);
}
```
```java
public interface Songwrtier { // 작곡가
    Song compose();
}
```
- 노래도 부를 수 있고, 작곡도 할 수 있는 싱어송라이터는 어떨까요?
```java
// Singer와 Songwriter가 모두 인터페이스이기 때문에
// 이 두가지를 확장한 새로운 타입인 SingerSongwriter를 정의할 수 있습니다.
public interface SingerSongwriter extends Singer, Songwrtier {
    AudioClip strum(); // strum: (기타 같은 것을) 치다
    void actSensitive();
}
```
- 인터페이스는 래퍼 클래스 관용구(#18)와 함께 사용한다면, **기능을 향상시키는 안전하고 강력한 수단**이 됩니다.

### 디폴트 메소드의 제약
- 인터페이스에 구현 방법이 명확한 기능이 있다면, 디폴트 메소드로 제공하는 것이 좋습니다.
- 하지만, 몇가지 제약이 있습니다.
0. 제약보다는 권장사항! ```@implSpec``` 자바독 태그를 붙여 문서화합시다. (#19)
1. **```Object``` 클래스의 메소드를 디폴트 메소드로 제공하면 안됩니다!**
    - https://stackoverflow.com/questions/24016962/java8-why-is-it-forbidden-to-define-a-default-method-for-a-method-from-java-lan
> 요약: 모든 클래스는 기본적으로 ```Object```를 상속합니다. 만약 ```Object```의 메소드 Q를 디폴트 메소드 W로 정의한 인터페이스 A를 구현한 클래스 B가 있다면 B는 W가 아닌 ```Object```의 메소드 Q를 우선으로 사용합니다. 즉, 이러한 디폴트 메소드들은 유효성이 없게 됩니다.
2. 인터페이스는 인스턴스 필드와 public이 아닌 정적 멤버를 가질 수 없습니다. (private 정적 메소드는 예외)
3. 우리가 만들지 않은 인터페이스에는 디폴트 메서드를 추가할 수 없습니다.

### 골격 구현(skeletal implementation) 클래스
- 인터페이스와 추상클래스의 장점을 모두 취할 수 있습니다. (템플릿 메소드 패턴)
    - 인터페이스로는 타입을 정의하고, 필요하면 디폴트 메소드도 추가
    - 골격 구현 클래스는 나머지 메소드들을 구현
- naming 규칙:  관례상 ```Abstract{클래스}```로 짓습니다.
- 예시) ```AbstractCollection```, ```AbstractSet```, ```AbstractList```, ...
- ```Collection```, ```Set```, ```List``` 인터페이스를 구현하는 것보다는 골격 구현 클래스를 이용하는 것이 훨씬 편합니다.
    - 우리가 자주 사용하는 자바의 ```HashSet```, ```TreeSet```도 ```AbstractSet```을 상속했습니다.
- 구조상 골격 구현을 확장하기 어렵다면, 인터페이스를 직접 구현해야합니다.
- 혹은, 골격 구현 클래스를 우회적으로 이용할 수 있습니다. : ```Simulated multiple inheritance```
    0. #18 의 래퍼 클래스와 비슷
    1. 인터페이스를 구현한 클래스에서 해당 골격 구현을 확장한 private 내부 클래스를 정의
    2. 각 메소드 호출을 내부 클래스의 인스턴스로 전달

### 골격 구현 클래스는 어떻게 작성하지?
1. 인터페이스의 메소드를 보며 다른 메소드들의 구현에 사용되는 '기반 메소드'를 선정
    - 기반 메소드들은 골격 구현에서 abstract가 될 것입니다.
2. 기반 메소드들을 사용하여 직접 구현이 가능한 메소드는 모두 디폴트 메소드로 제공합니다.
    - ```Object```의 메소드는 안돼요!
    - 만약 인터페이스의 모든 메소드가 기반 혹은 디폴트 메소드라면 골격 구현 클래스는 따로 만들지 않아도 됩니다.
3. 기반 메소드나 디폴트 메소드로 만들지 못한 메소드들은 골격 구현 클래스에서 추가로 구현합니다.
4. 기본적으로 상속해서 사용하는 것을 가정하므로, #19 의 설계 및 문서화 지침을 모두 따라야합니다.
```java
public abstract class AbstractMapEntry<K,V> implements Map.Entry<K,V> {
    // getKey, getValue는 확실한 기반 메소드
    
    // 변경 가능한 엔트리는 이 메소드를 반드시 override해야 한다.
    @Override
    public V setValue(V value) {
        throw new UnsupportedOperationException();
    }
    
    // 인터페이스에 equals와 hashCode의 동작 방식이 정의되어있다.
    // 하지만 default 메소드로 제공되면 안되므로,
    // 골격 구현 클래스에서 구현한다.
    @Override
    public boolean equals(Object obj) {
        // Map.Entry.equals의 일반 규약을 구현한 내용
        // 생략
    }

    @Override
    public int hashCode() {
        // Map.Entry.hashCode의 일반 규약을 구현한 내용
        // 생략
    }
    
    // toString도 기반 메소드를 이용하여 구현한다.
    @Override
    public String toString() {
        return getKey() + "=" + getValue();
    }
}
```

### 단순 구현(Simple implementation)이란?
- 골격 구현의 작은 변종으로, 쉽게 말하자면 '동작하는 가장 단순한 구현'입니다.
- 상속을 위해 인터페이스를 구현한 건 같지만, 추상 클래스가 아니란 점이 골격 구현과 다릅니다.
- java.util의 ```AbstractMap.SimpleEntry```를 참고해주세요.

**Comment by madplay** [comment]
- 혹시나하여 
```java
public interface testInteface {
    public static String b = "123"; // Okay
    private static String a = "123"; // Error
    public String c; // Error
}
