### ISSUE TITLE
아이템 21. 인터페이스는 구현하는 쪽을 생각해 설계하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#21]

**Comment by enochyeon** [comment]
## 인터페이스
### 사용 시 불편했던 점
* 이미 구현한 객체에 컴파일 오류가 생길 수 있기 때문에 새로운 메서드 추가가할 수 없음
### 개선
* 자바8에서 **default** 기능 추가
* 핵심 컬렉션 인터페이스들에 다수의 default 메서드 추가됨. 대부분 람다를 활용하기 위한 목적.
* but, **모든 상황에서** 불변식을 해치지 않는 디폴트 메서드를 작성하기는 쉽지 않다.

---

## 인터페이스의 default 메서드
### 잘 구현된 예
#### 코드 21-1 자바 8의 Collection 인터페이스에 추가된 디폴트 메서드
```java
default boolean removeIf(Predicate<? super E> filter) {
        Objects.requireNonNull(filter);
        boolean removed = false;
        final Iterator<E> each = iterator();
        while (each.hasNext()) {
            if (filter.test(each.next())) {
                each.remove();
                removed = true;
            }
        }
        return removed;
    }
```

### 기존 구현체와 잘 어우러지지 않는 경우
* org.apache.commons.collections4.collection.SynchronizedCollection
  * 기존 컬렉션 대신 클라이언트가 제공한 객체로 락을 거는 능력을 추가로 제공하는 기능이 있음(#18)
  * removeIf를 재정의하고 있지 않음
  * 알아서 동기화 해줄주지 못함.
  * SynchronizedCollection 인스턴스를 여러 스레드가 공유하는 환경에서 removeIf 호출 시 ConcurrentModificationException 발생하거나 다른 이슈 발생 가능
* Java 내부 구현체에서는 재정의하고 있나, 제3의 구현체들은 확인되지 않음

---

## 결론

* 많은 default 메서드가 추가되어 영향받는 코드가 생길 수 있음.
* 가능하면 default 메서드로 새 메서드를 추가하지는 말자.
* 새로운 인터페이스를 만들때는 유용함(#20).
* 기존 기능을 제거하거나 시그니처를 수정할 목적으로 사용하면 안됨.
* **인터페이스를 설계할 때는 세심한 주의를~!!**
* **테스트 많이 많이~**
