### ISSUE TITLE
아이템 22. 인터페이스는 타입을 정의하는 용도로만 사용하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#22]

**Comment by fairsun** [comment]
- 자신을 구현한 클래스의 인스턴스를 참조할 수 있는 타입 역할
- 클래스가 어떤 인터페이스를 구현한다는 것은 자신의 인스턴스로 무엇을 할 수 있는지를 클라이언트에 애기해주는 것

## 잘못 사용된 경우 

### 상수 인터페이스
- 상수는 클래스의 내부에서 사용하는 것인데 인터페이스를 구현했기때문에 내부 구현을 클래스의 API로 노출한 행위
~~~java
public interface PhysicalConstants {
    static final double AVOGADROS_NUMBER = 6.022_140_857e23;
    static final double BOLTZMANN_NUMBER = 1.380_648_52e-23;
    static final double ELECTRON_NUMBER = 9.109_383_56e-31;
}
~~~
- 자파 플랫폼 라이브러리에도 상수 인터페이스가 존재
    - https://docs.oracle.com/javase/7/docs/api/java/io/ObjectStreamConstants.html
    - 따라 사용하지 말 것.

## 상수를 공개할 목적 대안책
### 클래스나 인터페이스 자체에 추가
- ex> Integer와 Double 의 MIN_VALUE와 MAX_VALUE
### 열거 타입(#34)
- 열거 타입으로 나타내기 적합한 상수라면 열거 타입으로 공개
- enum class
### 유틸리티 클래스(#4)
- 인스턴스화할 수 없는 유틸리티 클래스를 구현해 공개
~~~java
public class PhysicalConstants {
    private PhysicalConstants() {}
    static final double AVOGADROS_NUMBER = 6.022_140_857e23;
    static final double BOLTZMANN_NUMBER = 1.380_648_52e-23;
    static final double ELECTRON_NUMBER = 9.109_383_56e-31;
}
~~~
- 유틸리티 클래스 사용할 경우 
~~~java
public class Test {
    double atoms(double mols) {
        return PhysicalConstants.AVOGADROS_NUMBER * mols;
    }
}
~~~
- 정적 임포트를 사용하여 클래스 이름 생략
~~~java
import static PhysicalConstants.*;

public class Test {
    double atoms(double mols) {
        return AVOGADROS_NUMBER * mols;
    }
}
~~~
## 결론
> 인터페이스는 타입을 정의하는 용도로만 사용해야 한다. 상수 공개용 수단으로 사용하지 말자.
