### ISSUE TITLE
아이템 27. 비검사 경고를 제거하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#27]

**Comment by gaepury** [comment]
## 할 수 있는 한 모든 비검사 경고를 제거하라!!
- 모두 제거한다면 그 코드는 타입 안정성이 보장된다.
- 비검사 경고(ex. warning: [unchecked] unchecked ...)를 제거할수록 타입 안정성이 높아진다고 볼 수 있다. 만약 타입 안정성이 확실한데 컴파일러의 경고를 없애고 싶다면 @SuppressWarnings("unchecked")를 사용하자. 로그에 파묻혀서 필요한 로그를 발견하기 어렵게 하지않도록 말이다.
   - 대신 타입 안정성을 검증하자!
   - 그렇지 않으면 런타임에 ClassCastException 발생 가능성이 높아짐.

### 수많은 제네릭 관련 컴파일러 경고들..
- 비검사 형변환 경고
- 비검사 메서드 호출 경고
- 비검사 매개변수화 가변인수 타입 경고
- 비검사 변환 경고등..

<br/>

## @SuppressWarnings 애너테이션은 항상 가능한 한 좁은 범위에 적용하자.
   -  메소드레벨, 클래스레벨보단 비검사 경고가 뜨는 지역변수 레벨에 다는 것이 가장 좋다. 
      - But 실무에서도 클래스 레벨에 다는 경우가 많음..
      - 권장
![image](https://user-images.githubusercontent.com/20143765/50979930-e5d8fc00-153a-11e9-84f6-102be8fdde17.png)
         - intellij에서 serial version uid 자동 생성하기 : http://vertex210.blogspot.com/2017/09/intellij-idea-serialversionuid.html

   - 애너테이션은 선언에만 달수 있기 때문에 return문에는 @SuppressWarnings 불가능
      - 지역변수를 선언하고 그 변수에 애너테이션을 달아주자  

<br/>

## @SuppressWarnings("unchecked") 애너테이션을 사용할 때면 그 경고를 무시해도 안전한 이유와 근거를 주석으로 남기자
