### ISSUE TITLE
아이템 28. 배열보다는 리스트를 사용하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#28]

**Comment by nypark425** [comment]
### 배열 vs 제네릭
1. 배열은 공변(covariant)이고, 제네릭은 불공변(invariant)입니다.
    
    > 공변: 함께 변한다
    - ```Sub```은 ```Super```의 하위 타입
    - ```Sub[]```도 ```Super[]```의 하위 타입
    - 하지만! ```List<Sub>```은 ```List<Super>```의 하위 타입도, 상위 타입도 아닙니다.
    ```java
    // 런타임에 실패한다.
    Object[] objectArray = new Long[1];
    objectArray[0] = "타입이 달라 넣을 수가 없다."; // ArrayStoreExxception 발생

    // 컴파일되지 않는다.
    List<Object> objectList = new ArrayList<Long>(); // 호환되지 않는 타입이다.
    objectList.add("타입이 달라 넣을 수가 없다.");
    ```
    - Long 저장소에 String을 넣기란 불가능
    - 하지만 배열은 런타임에서 오류가 발생하고, 제네릭을 이용한 리스트는 컴파일 타임 때 미리 알 수 있습니다.

2. 배열은 실체화(reify)됩니다.
    - 배열은 런타임에도 원소의 타입을 인지합니다.
        - 런타임 때 Long[]에 String 넣는 것을 실패한 걸 보면...
    - 하지만 제네릭은 타입 정보를 컴파일 타임에만 인지하며, 런타임 시 소거(erasure)됩니다.
        > 소거(erasure) : 제네릭이 지원되기 전, 레거시 코드와 제네릭 타입을 함께 사용할 수 있도록 한 매커니즘 (#26) ([oracle docs](https://docs.oracle.com/javase/tutorial/java/generics/erasure.html))

- 결국, 배열과 제네릭은 친해질 수 없는 관계입니다.
```java
// 배열은 아래처럼 사용하면 컴파일 오류가 발생합니다.
new List<E>[]; // 제네릭 타입
new List<String>[]; // 매개변수화 타입
new E[]; // 타입 매개변수
```

### 왜 제네릭 배열을 생성하지 못하게 했을까?
- **type safe하지 않기 때문**입니다.
```java
List<String>[] stringLists = new List<String>[1];   // (1) 제네릭 배열이 허용된다고 하자.
List<Integer> intList = List.of(42);                // (2) List.of: java 9 문법
Object[] objects = stringLists;                     // (3)
objects[0] = intList;                               // (4)
String s = stringLists[0].get(0);                   // (5)
```
- (2) : 원소가 하나인 List<Integer>를 생성합니다.
- (3) : (1)을 Object[]에 할당합니다. 배열은 공변이므로 문제가 없습니다.
- (4)
    - (2)의 인스턴스를 Object[]의 첫 원소로 지정합니다.
    - 제네릭의 소거 특성으로 인해 런타임시 List<Integer>는 List, List<String>[]는 List[]가 됩니다. 
    - 그래서 ArrayStoreException이 발생하지 않습니다.
- (5)가 문제입니다.
    - (1)에서 List<String>만 담겠다고 했는데, List<Integer>인 (2)가 저장되어있습니다.
    - (5)에서 (1)의 첫번째 원소(```stringLists[0]```)의 첫번째 원소(```].get(0)```)를 꺼낸 후, String으로 형변환하려고 합니다.
    - 하지만 꺼낸 원소는 Integer이므로, ClassCastException이 발생합니다.
- 그래서! 이런 일을 방지하려면 (1)에서 컴파일 오류가 나야합니다.

### 실체화 불가 타입(non-reifiable type)
- ```E```, ```List<E>```, ```List<String>``` 등
- 제네릭의 소거로 인해 실체화되지 않아서 런타임 시 컴파일타임보다 타입 정보를 적게 갖는 타입 ([oracle docs](https://docs.oracle.com/javase/tutorial/java/generics/nonReifiableVarargsType.html#non-reifiable-types))

### 제네릭 배열을 사용할 수 없어서 생기는 불편한 점들
- 제네릭 컬렉션에서는 원소 타입을 담은 배열을 반환하는 것이 보통은 불가능합니다. (#33 에서 해결 방법을 설명합니다.)
- 가변인수 메서드를 호출할 때 마다 가변인수 매개변수를 담을 배열이 생성되는데, 만약 그 배열의 원소가 실체화 불가 타입이라면 경고가 발생합니다. (#32 에서 ```@SafeVarargs```를 통해 대처할 수 있습니다.)

### 배열로 형변환 시 오류가 발생한다면, ```E[]```대신 ```List<E>```를 사용해보자.
```java
public class Chooser {
    private final Object[] choiceArray;
    
    public Chooser(Collection choices) {
        this.choiceArray = choices.toArray();
    }
    
    // 이 메서드를 사용하는 곳에서는 매번 형변환이 필요하다.
    // 형변환 오류의 가능성이 있다.
    public Object choose() {
        Random rnd = ThreadLocalRandom.current();
        return choiceArray[rnd.nextInt(choiceArray.length)];
    }
}
```
- 제네릭을 사용해보자.
```java
public class Chooser<T> {
    private final T[] choiceArray;

    public Chooser(Collection<T> choices) {
        this.choiceArray = choices.toArray();
    }

    // 동일한 choose 메소드
}
```
- 컴파일해보면? 오류가 발생하는군요.
```
> this.choiceArray = choices.toArray();
Error:(30, 43) java: incompatible types: java.lang.Object[] cannot be converted to T[]
```
- 걱정마세요! ```Object[]```를 ```T[]```로 형변환하면 됩니다.
```java
this.choiceArray = (T[]) choices.toArray();  // unchecked cast 경고 발생
```
- 이번엔 unchecked cast 경고가 발생합니다.
    - T가 무슨 타입인지 알 수 없으니, 이 형변환이 런타임에도 안전한지 보장할 수가 없기 때문입니다.
    - **제네릭은 타입 소거 특성으로 인해 런타임 시에 무슨 타입인지를 알 수 없기 때문임**을 기억합시다!!
- 코드는 경고만 발생할 뿐, 동작은 합니다. 어노테이션으로 경고를 숨겨도 되지만, 이왕이면 원인을 제거합시다. (#27)
- 이런 unchecked cast 경고를 제거하려면? 배열 대신 **리스트**를 사용하면 됩니다.
```java
class Chooser<T> {
    private final List<T> choiceList;

    public Chooser(Collection<T> choices) {
        this.choiceList = new ArrayList<>(choices);
    }

    public T choose() {
        Random rnd = ThreadLocalRandom.current();
        return choiceList.get(rnd.nextInt(choiceList.size()));
    }
}
```
