### ISSUE TITLE
아이템 3. PRIVATE 생성자나 열거 타입으로 싱글턴임을 보증하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#3]
싱글톤 : 싱글턴(singleton)이란 인스턴스를 오직 하나만 생성할 수 있는 클래스

## 싱글톤을 만드는 3가지 방식
1. public static final 필드 방식
2. 정적팩터리 방식의
3. Enum 방식

### 3.1 public static final 필드 방식의 싱글턴
```
public class Elvis {
    public static final Elvis INSTANCE = new Elvis();
    private Elvis() {...}
    public void leaveTheBuilding() {...}
}
```
private 생성자는 public static final 필드인 static 영역를 초기화할때 한번만 호출. 

#### 위 방식에서 이슈 두가지
1) 리플렉션 API AccesibleObject.setAccessible을 사용해 만들시 private 생성자 호출에 의해 싱글톤이 깨진다.
2) 직렬화, 역직렬화시 싱글톤이 깨진다.

- 리플렉션 API를 사용해 만들시 private 생성자 호출에 의해 싱글톤이 깨진다.
![image](https://user-images.githubusercontent.com/20143765/49223616-97f0b480-f422-11e8-927e-7aec56a9c926.png)
   - 결과가 다르다.
![image](https://user-images.githubusercontent.com/20143765/49223644-a939c100-f422-11e8-8317-2c33730cbfe5.png)

   - 해결법 : 생성자 수정
![image](https://user-images.githubusercontent.com/20143765/49223697-ca9aad00-f422-11e8-89f5-2f939be634b4.png)

- 직렬화, 역직렬화시 싱글톤이 깨진다. 
![image](https://user-images.githubusercontent.com/20143765/49223748-06ce0d80-f423-11e8-9d28-4c5480d64f3c.png)
 

   - 마찬가지로 결과가 다르다
![image](https://user-images.githubusercontent.com/20143765/49223777-19e0dd80-f423-11e8-984e-8268808972ad.png)

   - 해결법 : 생성자 방어로직으로는 해결 안됨. transient 키워드 추가하고, readResolve()를 구현하여 진짜 Elvis 반환
![image](https://user-images.githubusercontent.com/20143765/49224245-40534880-f424-11e8-8eb5-8f3a3feb9c1e.png)

### 3.2 정적 팩터리 방식의 싱글턴
```
public class Elvis {
    private static final Elvis INSTANCE = new Elvis();
    private Elvis() {...}
    public static Elvis getInstance() {return INSTANCE; }
    public void leaveTheBuilding() {...}
}
```
- 장점
   - 싱글턴임이 API의 명백히 드러나고, API 변경에 매우 유연
   - 정적팩터리를 제너릭 싱글턴 팩터리로 만들수 있다.(Item30)
   - 람다식 메소드 레퍼런스로 Elvis::getInstance처럼 사용이 가능하다.
- 단점
   - 리플렉션 API, 직렬화, 역직렬화 문제는 똑같다.

### 3.3 Enum 방식의 싱글턴
```
public enum Elvis {
    INSTANCE;
    public void leaveTheBuilding() {...}
}
```
   - 위에서 발생했던 리플렉션, 직렬화로 인한 문제가 전혀 없으며 구현법이 매우 간단.

---
## 추가사항
위에서 사용한 3-1, 3-2 방법들은 인스턴스를 미리 만드는 방식이며, 불필요한 시스템 리소스를 낭비할 가능성이 있다.
그래서 보통 아래와 같이 lazy initialization을 진행
```
class Singleton {
    private static Singleton ourInstance = null;
    public static Singleton getInstance() {
        if (ourInstance == null) {
            ourInstance = new Singleton();
        }
        return ourInstance;
    }
    private Singleton() {}
}
```
- 하지만 이 코드는 멀티 스레드 환경에서 적절하지 않음. 스레드가 경합하는 과정중에 인스턴스가 여러개 생성될수 있음

#### 3가지 해결책.

1) checking lock singleton
```
class Singleton {
    private static Singleton ourInstance = null;
    public static synchronized Singleton getInstance() {
        if (ourInstance == null) {
            ourInstance = new Singleton();
        }
        return ourInstance;
    }
    private Singleton() {}
}
```
- synchronized를 사용한 동기화. 메서드를 동기화시키면 성능 악화
2) double checking lock(DCL singleton)
```
class Singleton {
    private static Singleton ourInstance = null;
    public static Singleton getInstance() {
        if (ourInstance == null) {
            synchronized (Singleton.class) {
                if (ourInstance == null) {
                    ourInstance = new Singleton();
                }
            }
        }
        return ourInstance;
    }
    private Singleton() {}
}
```
처음 생성 이후에 synchronized block을 안타므로 성능 완화. 하지만 완벽한 방법이 아님.

3) LazyHolder 기법
```
class Singleton {
    private Singleton() {}

    public static Singleton getInstance() {
        return LazyHolder.INSTANCE;
    }

    private static class LazyHolder {
        private static final Singleton INSTANCE = new Singleton();
    }
}
```
- LazyHolder 기법으로 synchronized도 필요 없고, Singleton 클래스의 getInstance() 메서드에서 LazyHolder.INSTANCE를 참조하는 순간 Class가 로딩, 초기화가 진행되므로 불필요한 메모리 사용 방지.
ps : Class를 로딩하고 초기화하는 시점은 thread-safe를 보장하기 때문에 volatile이나 synchronized 같은 키워드가 없어도 된다..

**Comment by gaepury** [comment]
### readResolve는 ObjectInputstream이 stream에서 Object를 읽을때 호출

- The readResolve method is called when ObjectInputStream has read an object from the stream and is preparing to return it to the caller. ObjectInputStream checks whether the class of the object defines the readResolve method. If the method is defined, the readResolve method is called to allow the object in the stream to designate the object to be returned. The object returned should be of a type that is compatible with all uses. If it is not compatible, a ClassCastException will be thrown when the type mismatch is discovered.

### writeResolve는 ObjectOutputStream이 stream으로 Object를 쓸때 호출

**Comment by gaepury** [comment]
- Javap 
   - 클래스 파일을 원시 코드로 역어셈블해준다

- enum javap 결과
![image](https://user-images.githubusercontent.com/20143765/49269872-9cf94680-f4aa-11e8-83e0-77cdcf31790b.png)
