### ISSUE TITLE
아이템 31. 한정적 와일드카드를 사용해 API 유연성을 높이라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#31]

**Comment by seryang** [comment]
# 매개변수화 타입은 불공변(invariant) #28 
- `Sub`은 `Super`의 하위 타입
- `Sub[]`도 `Super[]`의 하위 타입
-하지만! `List<Sub>`은 `List<Super>`의 하위 타입도, 상위 타입도 아닙니다.
  - List`<String>`은 List`<object>`의 하위 타입이 아니라는 뜻
  - List`<Object>`에는 어떤 객체든 넣을 수 있지만, List`<String>`에는 문자열만 넣을 수 있음.
  - List`<String>`은 List`<Object>`가 하는 일을 제대로 수행하지 못하니 하위 타입이 될 수 없음
---
# 한정적 와일드카드를 사용하자
- #28 배열보다 리스트를 사용하라고 했음
   - 배열은 런타임에 원소의 타입을 인지
   - 제네릭은 타입 정보를 컴파일시 인지
- 하지만, 때론 불공변 방식보다 유연한 무언가가 필요하다

> case1. Stack의 pushAll 메서드 구현
```JAVA
public class Stack<E> {
    public Stack(){ ... };
    public void push(E e){ ... };
    public E pop() { ... };
    public boolean isEmpty(){ ... };

    // 와일드카드 타입을 사용하지 않은 pushAll 메서드 - 결함이 있다!
    public void pushAll(Iterable<E> src) {
         for (E e : src) 
               push(e);
   }
}
```
- Iterable src의 원소 타입이 스택의 원소 타입과 일치하면 잘 동작
```JAVA
Stack<Integer> integerStack = new Stack<>();
Iterable<Integer> intVal = List.of(3, 5);
integerStack.pushAll(intVal);  // ok
```
- 그럼 `Stack<Number>`로 선언한 후 pushAll(intVal)을 호출하면 어떻게 될까? 
  - intVal은 Integer 타입

```JAVA
Stack<Number> numberStack = new Stack<>();
Iterable<Integer> intVal = List.of(3, 5);
numberStack.pushAll(intVal);  // error
```
- Integer는 Number의 하위 타입이니 잘 동작할 것 같지만, 컴파일 에러 발생
   - incompatible types: `Iterable<Integer>` cannot be converted to `Iterable<Number>`
   - 매개변수화 타입이 불공변이기 때문

> 해결법 : 한정적 와일드카드 타입으로 변경
- pushAll의 입력 매개변수 타입은 'E의 Iterable'이 아니라 'E의 하위 타입의 Iterable'이어야 한다.
   - `Iterable<? extends E>`

```JAVA
// ok
public void pushAll(Iterable<? extends E> src) {
   for (E e : src) 
      push(e);
}
```

> case2. Stack의 popAll 메서드 구현
```JAVA
// 와일드카드 타입을 사용하지 않은 popAll 메서드 - 결함이 있다!
public void popAll(Collection<E> dst) {
   while (!isEmpty())
       dst.add(pop());
}
```
-  매개변수 Collection dst의 원소 타입이 스택의 원소 타입과 일치하면 잘 동작
```JAVA
Stack<Number> numberStack = new Stack<>();
Collection<Number> numberVals = ...;
numberStack.popAll(numberVals); // ok
```
- 그럼 `Stack<Integer>`로 선언한 후 popAll(numberVals)을 호출하면 어떻게 될까?
   - numberVals은 Number 타입
```JAVA
Stack<Integer> integerStack = new Stack<>();
Collection<Number> numberVals = ...;
integerStack.popAll(numberVals); // error
```
- `Collection <Number>`는 `Collection<Integer>`의 하위 타입이 아니므로 오류 발생 !

> 해결법 : 한정적 와일드카드 타입으로 변경
- popAll의 입력 매개변수의 타입이 'E의 Collection'이 아니라 'E의 상위 타입의 Collection'이어야 함
   - `Collection<? super E>`

```JAVA
// ok
public void popAll(Collection<? super E> dst) {
   while (!isEmpty())
       dst.add(pop());
}
```

## 공식 : 팩스(PECS) producer-extends, consumer-super
- 유연성을 극대화하려면 원소의 생산자나 소비자용 입력 매개변수에 와일드카드 타입을 사용하라 !
- 매개변수화 타입 T가 생산자라면 `<? extends T>`
    - ex) Stack에서 pushAll의 src 매개변수는 Stack이 사용하는 E 인스턴스를 생산하므로 extends
- 매개변수화 타입 T가 소비자라면 `<? super T>`
   - ex) Stack에서 popAll의 dst 매개변수는 Stack으로부터 E 인스턴스를 소비하므로 super
-  다만, 입력 매개변수가 생산자와 소비자 역할을 동시에 한다면 와일드카드 타입을 쓰지 말아야 함
   - 타입을 정확히 지정해야 하는 상황

> case3. #28 의 Chooser 생성자
```JAVA
class Chooser<T> {
    private final List<T> choiceList;

    public Chooser(Collection<T> choices) {
        this.choiceList = new ArrayList<>(choices);
    }
   ... 
}
```
- 생성자에 넘겨지는 choices 컬렉션은 T 타입의 값을 생산하기만 함
- `Chooser<Number>`의 생성자에 `List<Integer>`를 매개변수로 넘긴다면?
   - **컴파일 에러**

> 해결법 : PECS 공식에 따라 매개변수 Collection 원소 타입이 생산자이므로 Producer-extends 규칙에 따라 변경
```JAVA
public Chooser(Collection<? extends T> choices){...} // ok
```
- `Chooser<Number>`의 생성자에 `List<Integer>`를 매개변수로 넘길 수 있게 됨

> case4. #30-2 unoin 메서드
```JAVA
public class GenericMethodTest {
    public static <E> Set<E> union(Set<E> s1, Set<E> s2) {
        Set<E> result = new HashSet<>(s1);
        result.addAll(s2);
        return result;
    }

    public static void main(String[] args) {
        Set<Integer> integers = Set.of(1, 3, 5);
       Set<Double> doubles = Set.of(2.0, 4.0, 6.0);
       Set<Number> numbers = union(integers, doubles); // error
    }
}
```
- 매개변수 s1은 `Set<Integer>`, s2는 `Set<Double>` / 반환타입은 `Set<Number>`
   - `Set<Integer>`와 `Set<Double>`은 `Set<Number>`의 상위 타입도 하위타입도 아님 (타입 불공변)
> 해결법 : s1과 s2 모두 E의 생산자이니 PECS 공식에 의하여 다음과 같이 수정해야함
```JAVA
public static <E> Set<E> union(Set<? extends E> s1, Set<? extends E> s2){ ... }
```
- 자바 8부터만 제대로 컴파일 됨 (그 이하는 x)
- 자바 7은 타입 추론 능력이 강력하지 못해서 문맥에 맞는 반환 타입을 명시해야함
   - 앞 코드에서 union 호출의 반환 타입은 `Set<Number>`이다. 
   - 하지만 자바 7까지는 위 코드를 컴파일하면 다음과 같은 오류 메시지 발생
![image](https://user-images.githubusercontent.com/7028121/52635505-6493d100-2f0d-11e9-830b-44bc7c0479f6.png)

> 컴파일러가 올바른 타입을 추론하지 못한다면, **명시적** 타입 인수 사용하여 해결 (자바5 / 6 / 7 버전)
```JAVA
Set<Number> numbers = GenericMethodTest.<Number>union(integers, doubles);
```

> 여기서 주의 !
- 반환 타입은 여전히 `Set<E>` 
- 반환 타입에는 한정적 와일드카드 타입을 사용하면 안된다.
    - 클라이언트 코드에서도 와일드카드 타입을 써야 함

> case5. #30-7의 max 메서드
```JAVA
// 원래 버전
public static <E extends Comparable<E>> E max(List<E> list)

// 와일드카드 타입 사용
public static <E extends Comparable<? super E>> E max(List<? extends E> list)
```
- PECS 공식을 두번 적용
   - 입력 매개변수 : `List<E> list -> List<? extends E> `
        - E 인스턴스를 생산하므로 Producer-Extends 공식에 의해 수정되어짐
   - 타입 매개변수 : `<E extends Comparable> -> <E extends Comparable<? super E>>`
       - 처음 E가 `Comparable<E>`를 확장한다고 정의했는데, 이때` Comparable<E>`는 E 인스턴스를 소비한다
       - 그래서 Consumer-Super 공식에 의해 수정되어짐
      - Comparable은 언제나 소비자이므로, 일반적으로 `Comparable<E>`보다는 `Comparable<? super E>`를 사용 (Comparator도 마찬가지)

> 이렇게 복잡하게 만들 가치가 있는걸까? 
  - 다음 리스트는 오직 수정된 max로만 처리할 수 있음
```java
List<ScheduledFuture<?>> scheduledFutures = ...;
```
 - 수정 전 max는 ScheduledFuture가 `Comparable<ScheduledFuture>`를 구현하지 않았기 때문
 - [ScheduledFuture](https://docs.oracle.com/javase/8/docs/api/index.html?java/util/concurrent/ScheduledFuture.html)는 [Delayed](https://docs.oracle.com/javase/8/docs/api/index.html?java/util/concurrent/ScheduledFuture.html)의 하위 인터페이스, Delayed는 `Comparable<Delayed>`를 확장
```java
public interface Comparable<E>
public interface Delayed extends Comparable<Delayed>
public interface ScheduledFuture<V> extends Delayed, Future<V>
```
 - SchueduledFuture의 인스턴스는 다른 ScheduledFuture 인스턴스뿐 아니라 Delayed 인스턴스와도 비교할 수 있어서 수정 전 max가 이 리스트를 거부
   - 더 일반화하면, Comparable(혹은 Comparator)을 직접 구현하지 않고, 직접 구현한 다른 타입을 확장한 타입을 지원하기 위해 와일드카드가 필요
![image](https://user-images.githubusercontent.com/7028121/52780516-a51a5880-308d-11e9-9e89-2cff47a98056.png)

# 메서드 선언에 타입 매개변수가 한 번만 나오면 와일드카드로 대체하라 
- 메서드를 정의할 때 둘 중 어느 것을 사용해도 괜찮을 때가 많음
- 주어진 리스트에서 명시한 두 인덱스의 아이템들을 교환(swap)하는 정적 메서드를 두 방식으로 정의하면 다음과 같다
```java
// 1. 비한정적 타입 매개변수 사용
public static <E> void swar(List<E> list, int i, int j);

// 2. 비한정적 와일드카드 사용
public static void swap(List<?> list, int i, int j);
```
-public API라면 간단한 두번째가 나음
   - 어떤 리스트든 이 메서드에 넘기면 명시한 인덱스의 원소들을 교환 
   - 신경 써야 할 타입 매개변수도 없음

## 규칙 : 메서드 선언에 타입 매개변수가 한 번만 나오면 와일드카드로 대체하라 
  - 비한정적 타입 매개변수라면 비한정적 와일드카드로 바꾸고, 한정적 타입 매개변수라면 한정적 와일드카드로 바꿔라
  
> case1. 방금 꺼낸 원소를 리스트에 다시 넣는 코드
```java
public static void swap(List<?> list, int i, int j) {
    list.set(i, list.set(j, list.get(i))); // error
}
```
![image](https://user-images.githubusercontent.com/7028121/52780767-515c3f00-308e-11e9-8f06-a4030bedc4e7.png)
- 방금 꺼낸 원소를 리스트에 다시 넣을 수 없다는 뜻
-  `List<?>`에는 null 외에는 어떤 값도 넣을 수 없기 때문
> 해결법 : 와일드카드 타입의 실제 타입을 알려주는 메서드 구현하라
   - private 도우미 메서드로 따로 작성하여 활용하는 방법임
   - 실제 타입을 알아내려면 이 도우미 메서드는 제네릭 메서드여야 함
```java
public static void swap(List<?> list, int i, int j){
   swapHelper(list, i, j);
}

// 와일드카드 타입을 실제 타입으로 바꿔주는 private 도우미 메서드
private static <E> void swapHelper(List<E> list, int i, int j){
  list.set(i, list.set(j, list.get(i)));
}
```
- swapHelper 메서드는 리스트가 `List<E>`임을 알고 있음
   - 즉, 이 리스트에서 꺼낸 값은 항상 E이고, E타입의 값이라면 이 리스트에 넣어도 안전함을 알고 있음

# 정리
- 조금 복잡하더라도 와일드카드 타입을 적용하면 API가 훨씬 유연해진다!
- 널리 쓰일 라이브러리를 작성한다면 반드시 와일드카드 타입을 적절히 사용하자!
- PECS 공식을 기억하자!
- Comparable과 Comparator는 모두 소비자다!

**Comment by seryang** [comment]
# #Question
> 규칙 : 메서드 선언에 타입 매개변수가 한 번만 나오면 와일드카드로 대체하라 
```java
public static void swap(List<?> list, int i, int j) {
    list.set(i, list.set(j, list.get(i))); // error
}
```
- 방금 꺼낸 원소를 리스트에 다시 넣을 수 없어서 에러가 발생하는데 그 이유는 `List<?>에는 null 외에는 어떤 값도 넣을 수 없기 때문
- 그럼 해결책으로 와일드카드 타입의 실제 타입을 알려주는 메서드 구현하라 하였고, 다음과 같은 도우미 메서드를 구현하면 된다고 책에서는 소개함

```java
public static void swap(List<?> list, int i, int j){
   swapHelper(list, i, j);
}

private static <E> void swapHelper(List<E> list, int i, int j){
  list.set(i, list.set(j, list.get(i)));
}
```

- 여기서 swapHelper 메서드는 리스트가 List<E>임을 알고 있는데, 다시 말하면 이 리스트에서 꺼낸 값은 항상 E이고, E타입의 값이라면 이 리스트에 넣어도 안전함을 알고 있기 때문에 코드에 문제가 없어진다고 함.

- 여기서 궁금한게... 그럼 처음부터 (1-1의 입력 매개변수에 List<?>가 아닌 List<E>)
```java
public static void swap(List<E> list, int i, int j) {
    list.set(i, list.set(j, list.get(i)));
}
```
- 이런식으로 구현하면 문제 없지 않나요?
- 혹시 책에서 말하고자 하는 의도가 무엇인지 아시는 분 있다면 설명 부탁드립니다 (_ _)

---

#  #Answer

그런식으로 해도 문제없습니다.
실제로 와일드카드를 쓰는 대다수의 경우는 타입파라미터를 사용하는쪽으로도 해결이 가능합니다.
그럼 이 두개가 뭔 차이인지를 알아야하는데요.

타입파라미터는 타입을 캡쳐하고 와일드카드는 하지않습니다. 즉 메서드 내부에서 타입을 알아야하는경우는 타입파라미터를 쓰고, 타입을 몰라도 되는경우는 와일드카드를 쓰는걸 권합니다.

가령 List를 받아서 그 size를 리턴하는경우엔 List가 어떤 요소를 담고있든 중요하지않죠. 이럴땐 타입파라미터가 아니라 와일드카드를 권합니다.

그런 관점에서 봤을때 swap은 내부 요소가 어떤건지 알필요가 없습니다. 타입이 어떤거든 상관없이 요소들의 순서를 변경해주는거니까요. 그런데 개념적으로는 와일드카드가 맞는데 실제로 와일드카드로 구현하면 기술적 한계때문에 메서드 구현이 안됩니다. 개념과 기술의 충돌이 발생하는거죠. 이때 그냥 속편하게 기술쪽을 택하면 글쓴분이 말씀하시는것처럼 구현하게되는거고요. 개념을 지키면서 기술의 한계를 넘을때 저렇게 헬퍼 메서드를 만들어서 해결하는겁니다.

책에서 말하고자하는 의도는 '개념적 접근' 입니다. 실제로 Collection 을 사용하시다보면 메서드가 어떤건 타입파라미터로 되어있고 어떤건 와일드카드로 되어있는데 이때 와일드카드로 되어있는건 '아 얘네는 내부타입이 뭐든 신경쓰지않겠구나' 라고 이해하시면 됩니다.

참고 - https://okky.kr/article/549764?note=1624089
