### ISSUE TITLE
아이템 35. ORDINAL 메서드 대신 인스턴스 필드를 사용하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#35]

**Comment by gaepury** [comment]
### orinal을 잘못 사용한 예 - 따라하지 말 것!

![image](https://user-images.githubusercontent.com/20143765/51724008-b1b71c80-209e-11e9-92f5-f97af3c704b6.png)
- 열거타입은 해당상수가 그 열거 타입에서 몇번째 위치인지를 반환하는 ordinal이라는 메서드를 제공
- 동작은 하지만 유지보수하기 끔찍한 코드
   - 새로운 상수가 추가되거나 위치가 바꾸는 순간 numberOfMusicians 메서드를 오동작


---

### 간단한 해결책

```java
public enum Ensemble {
    SOLO(1), DUET(2), TRIO(3), QUARTET(4), QUINTET(5),
    SEXTET(6), SEPTET(7), OCTET(8), DOUBLE_QUARTET(8),
    NONET(9), DECTET(10), TRIPLE_QUARTET(12);

    private final int numberOfMusicians;
    Ensemble(int size) { this.numberOfMusicians = size; }
    public int numberOfMusicians() { return numberOfMusicians; }
}
```
- 열거 타입 상수에 연결된 값은 ordinal 메서드로 얻지 말고, 인스턴스 필드에 저장해서 사용.
- Enum의 API문서에 나와있는 ordinal 설명(아래 설명된 용도가 아니라면 ordinal 메서드는 절대(!) 사용하지 말자)
~~~
Most programmers will have no use for this method. It is designed for use by sophisticated enum-based data structures, such as EnumSet and EnumMap.
~~~
