### ISSUE TITLE
아이템 4. 인스턴스화를 막으려거든 PRIVATE 생성자를 사용하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#4]
### 모든 클래스들이 인스턴스화가 필요한 것은 아닙니다.
-  ```java.lang.Math```
- ```java.util.Array```
- ```java.util.Collections```
- static 필드/메소드만 있는 class
- final class 등

### 인스턴스화를 막으려면?
> 생성자를 정의 안하면 되지 않을까요?
> 클래스명에 Utility라고 써있고, 안에는 static 밖에 없으니까 괜찮을거에요!
```java
public class DateFormatUtility {
    private static String DATEFORMAT_DEFAULT = "yyyy-MM-dd HH:mm:ss";
    private static String DATEFORMAT_NO_TIME = "yyyy-MM-dd";
    
    // 생성자가 없다~
   
    public static String getDateformatDefault(Date date) {
        SimpleDateFormat dateFormatter = new SimpleDateFormat(DATEFORMAT_DEFAULT);
        return dateFormatter.format(date);
    }
    
    public static String getDateformatNoTime(Date date) {
        SimpleDateFormat dateFormatter = new SimpleDateFormat(DATEFORMAT_NO_TIME);
        return dateFormatter.format(date);
    }
}
```

### 하지만 누군가가 인스턴스화 해버린다면?
- 생성자를 명시하지 않으면, **컴파일러가 자동으로 기본 생성자**를 만듭니다.
```java
public static void main(String args[]) {
    Date today = new Date();
    // 이렇게 쓰기를 기대했는데...
    // String formattedDate = DateFormatUtility.getDateformatDefault(today);
    // 누군가 이렇게 써버린다면?? 불필요한 인스턴스가 발생합니다.
    DateFormatUtility dateFormatter = new DateFormatUtility();
    String formattedDate = dateFormatter.getDateformatDefault(today);
    System.out.println("Today Date: " + formattedDate);
}
```

### 어떻게 방지할까요? 간단합니다! 생성자를 private으로 선언해봅시다.
```java
public class DateFormatUtility {
    private static String DATEFORMAT_DEFAULT = "yyyy-MM-dd HH:mm:ss";
    private static String DATEFORMAT_NO_TIME = "yyyy-MM-dd";
    
    /**
     * 기본 생성자가 만들어지는 것을 막는다. (인스턴스화 방지용)
     */
    // 이렇게 주석까지 쓴다면? private만 선언된 것보다 더욱 명확해서 좋네요.
    private DateFormatUtility() {
        // 클래스 내부에서도 혹시나 생성자를 호출하는 것을 방지하려면
        // 에러를 명시적으로 던지는 것도 좋은 방법입니다.
        //  throw new AssertionError();
    }
    // static 메소드 생략
}
```

### 오~ 막아지는군요.
<img width="693" alt="2018-11-30 12 08 03" src="https://user-images.githubusercontent.com/10542786/49230981-49e4ac80-f434-11e8-935d-c76a5c102b5e.png">

> 이 클래스의 인스턴스화를 막는건 알겠어요. 그런데 누가 상속해서 인스턴스를 생성하면 어떡하죠?

### 걱정마세요. 상속도 방지합니다!
- 모든 생성자는 명시적이든, 묵시적이든 상위 클래스의 생성자를 호출하는데,
- private이니까 생성자 호출이 안되는 것이죠!
<img width="815" alt="2018-11-30 12 08 11" src="https://user-images.githubusercontent.com/10542786/49230983-4cdf9d00-f434-11e8-85fd-0f626e38a327.png">

**Comment by nypark425** [comment]
### 예시로 든 유틸성 java class들의 실제 내부
1. java.lang.Math
<img width="402" alt="2018-11-30 12 14 49" src="https://user-images.githubusercontent.com/10542786/49231362-22421400-f435-11e8-908a-ee037f589ee3.png">

2. java.util.Arrays
<img width="566" alt="2018-11-30 12 14 13" src="https://user-images.githubusercontent.com/10542786/49231398-3128c680-f435-11e8-99bb-03da2ff6ca56.png">

3. java.util.Collections
<img width="567" alt="2018-11-30 12 15 05" src="https://user-images.githubusercontent.com/10542786/49231447-4aca0e00-f435-11e8-8cbf-6a5da5b57103.png">
