### ISSUE TITLE
아이템 40. @OVERRIDE 애너테이션을 일관되게 사용하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#40]

**Comment by iknowchang** [comment]
@Override 
- 메소드 선언에만 달 수 있음.
- 상위 타입 메소드를 재정의 했다는 것을 의미

코드 40-1을 통한 설명
- [Bigram 소스 코드](https://github.com/jbloch/effective-java-3e-source-code/blob/master/src/effectivejava/chapter6/item40/Bigram.java)
- 코드의 출력 기대 값은 26이지만, 260 출력됨.
- 문제 : equas를 overloading 해버림. ( return이 Object 아님)
- @Override를 넣으면 compiler가 의도를 알고 compile error를 발생함
```
/Bigram.java:13: error: method does not override or implement a method from a supertype
@Override
^
1 error
```
- 아래 처럼 annotation 없이 구현해도 의도 대로 동작은 함. 
```
     public boolean equals(Object o) {
        if (!(o instanceof Bigram))
            return false;
        Bigram b = (Bigram) o;
        return b.first == first && b.second == second;
    }
```
- 제대로 하려면 위 코드에 @Override 까지 붙이자.

최종 원칙
- 재정의 하려는 모든 메서드에 @Override annotaion을 달자
- 예외 : 추상 메소드르 재정의 할때는 굳이 붙이지 않아도 됨. ( 이유 : 추상 메소드인데 구현하지 않으면 compiler 경고 줌 )

기타
- 인터페이스 default 메소드를 재구현한 메소드도 @Override 다는 습관 들이면 재차 확신 가능
```
 public interface Calculator {
        public int plus(int i, int j);
        public int multiple(int i, int j);
 
        default int exec(int i, int j){     
            return i + j;
        }
    }
```
- 인터페이스 default 메소드 없다면, 굳이 안달아도 되기는함. (이유 : 구현 안하면 compiler error 발생)
- 하지만,  IDE는 보통 추상과 관련없이 일관되게 @Override를 붙여준다.
- 모든 재정의에는 @Override 붙이기를 권장.
