### ISSUE TITLE
아이템 41. 정의하려는 것이 타입이라면 마커 인터페이스를 사용하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#41]

**Comment by duckcalf** [comment]
# 마커 인터페이스 vs. 마커 애너테이션

## 마커 인터페이스의 장점

1. 클래스의 인스턴스들을 구분하는 타입으로 쓸 수 있다.
마커 애너테이션으로 구현했다면, 런타임에서나 잡을 수 있는 에러를 인터페이스로 구현했다면, 컴파일 타임에서 잡을 수 있다!
하지만, ObjectOutputStream.writeObject 와 같이 Serializable을 받아야 하는데, 그냥 Object로 받은 경우에는 말짱 꽝이다.

2. 적용 대상을 더 정밀하게 지정할 수 있다.
마커 애너테이션의 적용대상(@Target)을 ElementType.TYEP으로 선언하더라도, 클래스/인터페이스/enum/애너테이션 모두에게 설정을 할 수 있지만, 마커 인터페이스는 클래스에만 설정할 수 있다.

책에서는 Set 역시 마커 인터페이스의 일종이라고 하지만, 동의하기 힘듬.. Set은 Collection과 다른 method(retainAll)가 존재함 

## 마커 애너테이션의 장점
1. 거대한 애너테이션 시스템의 지원을 받는다는 점
만약에, 애너테이션을 적극적으로 사용하는 프레임워크를 쓴다면, 일관성을 위해서 마커 애너테이션을 쓰는것도 좋을 수 있음

## 결론
마커 애너테이션을 만들때, "이 마킹이 된 객체를 매개변수로 받는 메서드를 작성할 일이 있을까?"라는 물음에 YES라면, 마커 인터페이스를 사용하길 권장함

**Comment by nypark425** [comment]
### 마커 인터페이스란?
> 마커 인터페이스는 메서드 선언이 없는 인터페이스이다. 
> 대표적인 마커 인터페이스로 Serializable과 Cloneable이 있다.
> [(출처)](https://programmingfbf7290.tistory.com/entry/%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-%EB%A7%88%EC%BB%A4Marker-%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4-%EC%96%B4%EB%85%B8%ED%85%8C%EC%9D%B4%EC%85%98Annotation-%ED%99%9C%EC%9A%A9)
