### ISSUE TITLE
아이템 42. 익명 클래스보다는 람다를 사용하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#42]

**Comment by madplay** [comment]
### 함수 객체
- 예전에는 함수 타입을 표현할 때 추상 메서드를 하나만 담은 인터페이스를 사용했다.
- 이러한 인터페이스의 인스턴스를 함수 객체(function Object)라고 하여 특정 함수나 동작을 나타냈다.
<br/><br/>

### 익명 클래스 - 고전 방식
- ```JDK 1.1``` 부터는 함수 객체를 만드는 주요 방법으로 익명 클래스를 사용했다.
- 익명 클래스를 사용하는 방법
```java
// 리스트 words가 있다고 가정한다.
Collections.sort(words, new Comparator<String>() {
    public int compare(String s1, String s2) {
        return Integer.compare(s1.length(), s2.length());
    }
});
```
- 익명 클래스 방식은 코드가 너무 길기 때문에 자바는 함수형 프로그래밍에 적합하지 않았다.

### 람다(lambda)
- ```JDK 1.8``` 부터는 추상 메서드 하나 짜리 인터페이스, 그러니까 함수형 인터페이스!
- 그들의 인스턴스를 람다식(lambda expression, 짧게 람다)라고 사용해 만들 수 있게 되었다.
- 일단 람다는 간결하다. 아래와 같이 정렬을 구현할 수 있다.
```java
Collections.sort(words,
    (s1, s2) -> Integer.compare(s1.length(), s2.length()));
```
- 여기서 람다의 타입은 ```(Comparator<String>)```
- 매개변수(s1, s2)의 타입은 ```String```
- 반환값의 타입은 ```int```
- 그런데 코드 상에서는 명시되어 있지 않다.
- 컴파일러가 문맥을 살펴 타입을 추론한 것이다!
  - 상황에 따라 컴파일러가 타입을 결정하지 못할 수도 있는데, 그럴 때는 명시해야 한다.
  - 그러니까 타입을 명시해야 코드가 명확할 때를 제외하고는 람다의 모든 매개변수 타입은 생략하자!
> 컴파일러가 타입을 추론하는 데 필요한 타입 정보 대부분을 제네릭에서 얻는다. 그래서 우리가 이 정보를 제공하지 않으면 컴파일러는 람다의 타입 추론을 할 수 없게 되어 개발자가 일일이 명시해야 한다.

- 위의 코드는 더 간결하게 만들 수 있다.
```java
Collections.sort(words, comparingInt(String::length));
```
- 조금 더 발전해서 ```JDK 1.8``` 이상으로 가면!
```java
// List 인터페이스에 추가된 sort 메서드를 사용할 수 있다.
words.sort(comparingInt(String::length));
```

<br/>

### enum과의 조합도 가능하다.
- https://github.com/NMP-Study/EffectiveJava/issues/34 에서 살펴본 enum을 바꿀 수 있다.
- 우선 기존의 enum은 아래와 같다.

```java
enum Operation {
    PLUS("+") { 
        public double apply(double x, double y) { return x + y; }
    },
    MINUS("-") {
        public double apply(double x, double y) { return x - y; }
    },
    TIMES("*") {
        public double apply(double x, double y) { return x * y; }
    },
    DIVIDE("/") {
        public double apply(double x, double y) { return x * y; }
    };
    
    private final String symbol;
   
    Operation(String symbol) { this.symbol = symbol; }
    
    @Override public String toString() { return symbol; } 
    public abstract double apply(double x, double y);
}
```

- 여기서 람다를 이용하면 열거 타입의 인스턴스 필드를 이용하는 방식으로 상수별로 다르게 동작하는 코드를 쉽게 구현 가능하다!
- 단순히 각 열거 타입 상수의 동작을 람다로 구현해 생성자에 넘기고 생성자는 이 람다를 인스턴스 필드로 저장해둔다.
> ....!? 코드로 이해하는게 더 빠르더라고요!
```java
public enum Operation {
    PLUS ("+", (x, y) -> x + y),
    MINUS ("-", (x, y) -> x - y),
    TIMES ("*", (x, y) -> x * y),
    DIVIDE ("/", (x, y) -> x / y);

    private final String symbol;
    private final DoubleBinaryOperator op;

    Operation(String symbol, DoubleBinaryOperator op) {
        this.symbol = symbol;
        this.op = op;
    }

    @Override public String toString() { return symbol; }

    public double apply(double x, double y) {
        return op.applyAsDouble(x, y);
    }
}

// 사용할 때는 이렇게 
// Operation.PLUS.apply(2, 3);
```
- DoubleBinaryOperator는 ```java.util.function``` 패키지에 있는 Double 타입 인수 2개를 받아 Double 타입 결과를 돌려주는 인터페이스

<br/>

### 그럼 람다의 단점은 무엇일까?
- 람다는 이름도 없고 문서화도 못 한다. 
- 그래서 코드 자체로 동작히 명확하게 설명되지 않거나 코드 줄 수가 많아지면 쓰지 말아야 한다.
- 람다가 길거나 읽기 어렵다면 쓰지 않는 쪽으로 리팩토링하는 걸 권장!

<br/>

### 그리고 람다가 대체 못하는 곳
- 추상 클래스의 인스턴스를 만들 때 람다를 쓸 수 없다. 익명 클래스를 써야 한다.
```java
abstract class Hello {
    public void sayHello() {
        System.out.println("Hello!");
    }
}

public class Main {
    public static void main(String[] args) {
        // 이건 원래 안되요~
        // Hello hello = new Hello();

        Hello instance1 = new Hello() {
            private String msg = "Hi";
            @Override public void sayHello() {
                System.out.println(msg);
            }
        };

        Hello instance2 = new Hello() {
            private String msg = "Hola";
            @Override public void sayHello() {
                System.out.println(msg);
            }
        };

        // Hi!
        instance1.sayHello();

        // Hola!
        instance2.sayHello();

        // false
        System.out.println(instance1 == instance2);
    }
}
```
- 자기 자신 참조가 안된다. ```this``` 키워드는 바깥 인스턴스를 가리킨다.
- 람다를 직렬화는 삼가야 한다. 구현별(가령 가상 머신별로) 직렬화 형태가 다를 수 있다.
  - 그럴 때는 ```private 정적 중첩 클래스```의 인스턴스를 사용하자. https://github.com/NMP-Study/EffectiveJava/issues/24

**Comment by enochyeon** [comment]
[람다가 이끌어 갈 모던 Java](https://d2.naver.com/helloworld/4911107) (참고)
