### ISSUE TITLE
아이템 43. 람다보다는 메서드 참조를 사용하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#43]

**Comment by gaepury** [comment]
## 메서드 참조 장점
함수 객체를 람다보다도 간결하게 만들수 있다.

```java
// 변경 전
map.merge(key, 1, (count, incr) -> count + incr)

// 변경 후 
map.merge(key, 1, Interger::sum);
```
- 단순히 int count + int incr 결과 값을 리턴해주는 기능만 해주기 때문에 이와 동일한 기능을 하는 Interger#sum 메서드 참조를 전달해서 구현가능

### Map merge 메서드 참고
```java
 default V merge(K key, V value,
            BiFunction<? super V, ? super V, ? extends V> remappingFunction)
```
- key 값을 받아 주어진 key가 map안에 없다면 value 값을 [key, value] 쌍으로 저장하고, key값을 받아 주어진 key가 map안에 있다면 value값을 BiFunction#apply 메서드에 적용한 다음 [key, BiFunction#apply 메서드의 결과] 쌍으로 저장


## 메서드 참조 단점
항상 메서드 참조가 좋은것은 아니다. 때론 람다가 메소드 참조보다 간결할 때가 있다.

ex1)
 ![image](https://user-images.githubusercontent.com/20143765/52833002-5072ee00-311e-11e9-9ea0-f815b4dc5e61.png)
   - 클래스명이 매우 길거나 명확하지 않은 경우에는 메소드참조를 쓰지 않는 것이 도움될 수도 있다.

ex2)
```java
// 변경 전 
Function.identity(); 

// 변경 후 
x -> x
```

## 메서드 참조 유형
#### From Effective java
![image](https://user-images.githubusercontent.com/20143765/52833356-b2802300-311f-11e9-9c8b-b29f51a0bbad.png)

#### From Oracle
![image](https://user-images.githubusercontent.com/20143765/52833379-c4fa5c80-311f-11e9-85cf-2053dcbd3453.png)

#### From My
1) static 메서드 참조 (x) -> ClassName.method(x) => ClassName::method
2) 인스턴스 메서드 참조 (obj, x)-> obj.method(x) => ClassName::method
3) 특정 객체 인스턴스메서드 참조 (x) -> obj.method(x) => obj::method

- 비한정적(인스턴스) 유형 (= 인스턴스 메서드 참조)에서는 첫번째 인자는 인스턴스가 되고, 두번째 인자부터는 인스턴스 메소드의 인자로 넣어 호출한다.
```java
(a, b) -> a.compareTo(b) = Integer::compareTo
```

## 참고(정훈님 블로그)
> userList.forEach(user -> System.out.println(user)); 이 코드의 콜스택을 보면 ArrayList.forEach -> Consumer.accept -> System.out.println 이다. 그런데, Consumer.accept 는 사실 필요없고, depth만 깊어지게 한다. 메소드 레퍼런스를 사용하면 이런 부분을 해결할 수 있다. userList.forEach(System.out::println);
https://sjh836.tistory.com/173?category=679845

## 핵심정리
메서드 참조는 람다의 간단명료한 대안이 될 수 있다. 메서드 참조 쪽이 짧고 명확하다면 메서드 참조를 쓰고, 그렇지 않을 때만 람다를 사용하라.
