### ISSUE TITLE
아이템 44. 표준 함수형 인터페이스를 사용하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#44]

**Comment by nypark425** [comment]
### 템플릿 메서드 패턴의 매력은 감소하고 있습니다.
> 템플릿 메서드 패턴 : 상위 클래스의 기본 메서드를 재정의하여 원하는 동작을 구현 ([참고](https://jdm.kr/blog/116))
- *Why?* Java가 람다를 지원하게 되었기 때문입니다.
- 이를 대체하는 요즘 스타일
    - "같은 효과의 함수 객체를 받는 static 팩토리나 생성자를 제공하는 것"입니다.

### 이게 무슨 말인가 하면...
```java
// LinkedHashMap.java > removeEldestEntry 메서드
protected boolean removeEldestEntry(Map.Entry<K,V> eldest) {
    return false;
}
```
- 이를 재정의하면 캐시로 사용할 수 있습니다. ([참고1](https://github.com/NMP-Study/EffectiveJava/issues/44#issuecomment-458980209))
```java
// LinkedHashMap.java > removeEldestEntry 메서드
@Override
protected boolean removeEldestEntry(Map.Entry<K,V> eldest) {
    // map의 사이즈가 100개를 넘는지 반환
    // 100개를 넘는다면 오래된 entry부터 제거
    return size() > 100;
}
```

### 람다 스타일로 해보자
- 오늘날 람다를 이용해서 다시 구현한다면, ```LinkedHashMap```는 함수 객체를 받는 static 팩토리나 생성자를 제공했을 겁니다.
- 위에서 override한 ```removeEledestEntry```는 ```size()```를 호출하는데, 이는 **인스턴스 메서드**라서 가능한 것!
- 팩터리나 생성자를 호출할 때는 *Map의 인스턴스가 존재하지 않기 때문*에, Map 자신도 함수 객체에 건네줘야 합니다.
```java
@FunctionalInterface interface EldestEntryRemovalFunction<K, V> {
    boolean remove(Map<K, V> map, Map.Entry<K, V> eldest);
}
```
> 불필요한 함수형 인터페이스 - 대신 '표준 함수형 인터페이스'를 사용해라.
- 번외) [함수형 인터페이스란?](https://github.com/NMP-Study/EffectiveJava/issues/44#issuecomment-463653419)

### 표준 함수형 인터페이스
- 위에서 만든 인터페이스를 굳이 사용할 이유는 없습니다.
    - 왜? ```java.util.function``` 패키지 하위에 이미 동일한 역할을 하는게 있기 때문이죠.
- 용도에 맞는 것이 있다면, 직접 구현하지 말고 **표준 함수형 인터페이스**를 활용하세요!
    - API 개발 시 관리하는 개념의 수가 줄어들어 관리가 편해짐
    - 제공되는 많은 유용한 디폴트 메서드
    - 다른 코드와의 상호운용성 상승

### 기본 인터페이스
- ```java.util.function``` 하위에는 약 43개의 인터페이스가 있습니다. (스샷은 일부만 가져왔어요.)
<img width="240" alt="2019-02-14 11 49 38" src="https://user-images.githubusercontent.com/10542786/52794526-54b5f180-30b3-11e9-88f2-7f94b71e393a.png">

- 이 모두를 기억하기 어려우니, **6개의 기본 인터페이스**만 기억합시다!
    - 모두 참조 타입용입니다.

| 인터페이스        | 의미                                                        | 함수 시그니처       | 예                  |
|-------------------|-------------------------------------------------------------|---------------------|---------------------|
| ```UnaryOperator<T>```  | 반환값과 인수의 타입이 같은 함수, 인수가 1개                | T apply(T t)        | String::toLowerCase |
| ```BinaryOperator<T>``` | 반환값과 인수의 타입이 같은 함수, 인수가 2개                | T apply(T t1, T t2) | BigInteger::add     |
| ```Predicate<T>```      | 인수 하나를 받아서 boolean을 반환하는 함수                  | boolean test(T t)   | Collection::isEmpty |
| ```Function<T,R>```     | 인수와 반환 타입이 다른 함수                                | R apply(T t)        | Arrays::asList      |
| ```Supplier<T>```      | 인수를 받지 않고 값을 반환/제공하는 함수                    | T get()             | Instant::now        |
| ```Consumer<T>```       | 인수를 하나 받고 반환값은 없으며, 특히 인수를 소비하는 함수 | void accept(T t)    | System.out::println |

### 기본 인터페이스의 변형
- 기본 인터페이스는 primitive type인 ```int, long, double```용으로 각 3개씩 변형이 생길 수 있습니다.
    - ```DoublePredicate```, ```IntConsumer```, ```LongSupplier```...
- 이중 유일하게 ```Function```의 변형의 반환 타입이 **매개변수화**되었습니다.
```java
@FunctionalInterface
public interface LongFunction<R> { R apply(long value); }

@FunctionalInterface
public interface IntFunction<R> { R apply(int value); }

@FunctionalInterface
public interface DoubleFunction<R> { R apply(double value); }
```
- 인수를 2개씩 받는 변형 : ```BiPredicate<T,U>```, ```BiFunction<T,U,R>```, ...
    - ```BiFunction```에는 다시 기본 타입을 반환하는 변형이 있습니다. : ```ToIntBiFunction<T,U>```, ...
- 그 외 나머지는 책 265~266쪽을 읽어주세요 :)

### 표준 함수형 인터페이스 사용 시 주의점!
- 기본 함수형 인터페이스에 **박싱된 기본 타입을 넣어 사용하지 맙시다!** (#61)
    - 동작은 하지만, 계산량이 많아지면 성능이 처참히 느려집니다.
- 필요한 용도가 없다면 직접 구현하면 됩니다.

### 하지만 구조적으로 동일한데도 전용 함수형 인터페이스를 직접 작성해야하는 경우도 있을까?
- 예로, ```Comparator```와 ```ToIntBiFunction```는 구조적으로 동일합니다.
    - 인자 두개를 받아서(Bi)
    - int를 반환하는(ToInt)
    - 인수와 반환 타입이 다른 함수(Function)
```java
// Comparator.java
@FunctionalInterface
public interface Comparator<T> {
	int compare(T o1, T o2);
	// override 및 default 메소드 생략
}
```
```java
// ToIntBiFunction.java
@FunctionalInterface
public interface ToIntBiFunction<T, U> {
    int applyAsInt(T t, U u);
}
```
- Comparator(1.2)가 ToIntBiFunction(1.8)보다 훨~씬 먼저 생기긴 했지만, 그래도 ToIntBiFunction를 사용하지 않았을거라고 합니다.
    - 첫째, 지금의 이름이 API에서 굉장히 자주 사용되는 그 용도를 아주 잘 설명해주고 있기 때문입니다.
    - 둘째, 구현하는 쪽에서 반드시 지켜야하는 규약을 담고 있습니다.
    - 셋째, 비교자들을 변환하고 조합해주는 유용한 디폴트 메서드들을 갖고 있습니다.
    - [(Comparator가 ToIntBiFunction를 extends해도 되지 않을까요..?;;)](https://github.com/NMP-Study/EffectiveJava/issues/44#issuecomment-463680307)
> 위에서 설명한 3가지 중 하나 이상을 만족한다면, 전용 함수 인터페이스를 고민해볼 필요는 있습니다.

### ```@FunctionalInterface```
- 이 어노테이션을 사용하는데에는 크게 3가지 목적이 있습니다.
    - 첫째, 어노테이션이 달린 인터페이스가 람다용으로 설계된 것임을 알려줍니다.
    - 둘째, 해당 인터페이스가 추상 메서드를 오직 하나만 가지고 있어야 컴파일됩니다.
    - 마지막으로, *둘째* 이유로 인해 누군가 실수로 메서드를 추가하지 못하게 방지합니다.
- **직접 만든 함수형 인터페이스에는 항상 ```@FunctionalInterface```를 사용합시다!**

### 함수형 인터페이스를 API에서 사용할 때 주의점!
- 서로 다른 함수형 인터페이스를 같은 위치의 인수로 받는 메서드를 다중 정의해서는 안됩니다.
    - 클라이언트에게 모호함을 안겨주며, 실제로 문제도 발생했었습니다.
- 아래 예시에서, submit 메서드를 사용할 때 형변환이 필요한 경우가 왕왕 생깁니다. (#52)
```java
public interface ExecutorService extends Executor {
    // submit 메서드는 Callable<T>와 Runnable를 각각 인수로 하여 다중정의했습니다.
    <T> Future<T> submit(Callable<T> task);
    Future<?> submit(Runnable task);
    // 나머지 생략
}
```

**Comment by nypark425** [comment]
## 참고 1
### LinkedHashMap > removeEldestEntry 예제
```java
public class Item44Application {
    public static void main(String[] args) {
        NewLinkedHashMap<String, String> hashMap = new NewLinkedHashMap<>();
        hashMap.put("a", "a");
        hashMap.put("b", "b");
        hashMap.put("c", "c");

        System.out.println(hashMap);
    }
}

class NewLinkedHashMap<K, V> extends LinkedHashMap<K, V> {
    @Override
    protected boolean removeEldestEntry(Map.Entry<K,V> eldest) {
        return size() > 2;
    }
}
```
- 결과
```
{b=b, c=c}
```

### 왜?
```java
// LinkedHashMap > afterNodeInsertion
void afterNodeInsertion(boolean evict) { // possibly remove eldest
    LinkedHashMap.Entry<K,V> first;
    if (evict && (first = head) != null && removeEldestEntry(first)) {
        K key = first.key;
        removeNode(hash(key), key, null, false, true);
    }
}
```
```java
public V put(K key, V value) {
    return putVal(hash(key), key, value, false, true); // 여기서 내부적으로 afterNodeInsertion 사용
}
```

**Comment by nypark425** [comment]
## 참고 2
### 번외) 함수형 인터페이스??
- 이 [블로그글](https://multifrontgarden.tistory.com/124?category=471239)을 추천드립니다.
> 람다 표현식으로 구현이 가능한 인터페이스는 오직 추상 메서드가 1개뿐인 인터페이스만 가능하며 그렇기때문에 추상 메서드가 1개인 인터페이스를 부르는 명칭이 추가됐다. 그것이 함수형 인터페이스다. 
> ```@FunctionalInterface```? 함수형 인터페이스에 추상 메소드를 추가하는 불상사를 막기 위한 어노테이션
```
Error:(9, 1) java: Unexpected @FunctionalInterface annotation
  nypark.study.effectivejava3.chapter7.item44.EldestEntryRemovalFunction is not a functional interface
    multiple non-overriding abstract methods found in interface nypark.study.effectivejava3.chapter7.item44.EldestEntryRemovalFunction
```

**Comment by nypark425** [comment]
## 참고 3) (+논의)
### ```Comparator```는 왜 ```ToIntBiFunction```을 사용하면 안될까?
- 책에서는 사용하면 안된다고 말하고, 3가지 이유를 설명했는데요.
- 아래 코드처럼 작성해보니 컴파일 오류는 발생하지 않습니다.
```java
// copy from Comparator
@FunctionalInterface
public interface FakeComparator<T> extends ToIntBiFunction<T,T> {
    // int compare(T o1, T o2);
    // 요거만 주석처리하면 컴파일 오류가 발생하지 않네요.

    default FakeComparator<T> thenComparing(FakeComparator<? super T> other) {
    	// 생략
    }
    
    // 그외 여러가지 default 메소드들...
}
```
- 그렇다면 왜 안되는걸까요?
    - ```compare``` 메소드 이름이 너무 좋은데 사용할 수가 없어서??;

### 혼자 생각해보니,
- 구조적으로 동일할 뿐, extends를 하는 것은 계층 구조상 의미에 맞지 않는게 아닐까합니다.
    - ```ToIntBiFunction```와 ```Comparator```는 ```is-a``` 관계(#18)가 아니니까요.
- 비슷한 논의 : [Why does Map<K,V> not extends Function<K,V>?](https://stackoverflow.com/questions/29388560/why-does-mapk-v-not-extends-functionk-v)
- 또 있을까요?
