### ISSUE TITLE
아이템 47. 반환 타입으로는 스트림보다 컬렉션이 낫다

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#47]

**Comment by seryang** [comment]
## 반환 타입으로 Collection이 Stream보다 나은 이유
```java
private static List<String> getList(){
   return dataList;
}

public static void main(String [] args){

  // 1. for문을 통한 반복
  for (String name : getList()){
      // do something
  } 

   // 2. Stream으로 변환 후 반복
   getList().stream().forEach(name -> {
       // do something
   });
}
```
- 반환 타입이 Collection인 경우 반복문 처리가 가능

```java
private static Stream<String> getStream() {
       return dataStream;
}

public static void main(String [] args){

  // compile error
  for (String name : getStream()){
      // do something
  } 
}
```
- 반환 타입이 Stream인 경우 for문으로 반복문을 처리할 수 없음
   - Stream이 Iterable을 확장(extends)하지 않기 때문

``` java
private static Stream<String> getStream() {
       return dataStream;
}

public static void main(String [] args){

  // Stream for-each 처리 
  for (String name : (Iterable<String>) getStream()::iterator){
      // do something
  } 
}
```
- Stream은 iterable interface가 정의한 추상 메서드를 전부 가지고 있어서 동일한 방식으로 동작
- 따라서 메서드 참조(Stream::iterator)를 적절히 형 변환(Iterable<String>)해주면 for-each문 사용 가능

## [정리] Collection이 Stream 보다 좋은 이유
- 작동은 하지만 너무 난잡하고 직관성이 떨어짐
- Collection일 경우 Iterable 하위 타입이고, stream 메서드도 지원하고 있음
- 공개 API의 반환 타입에는 Collection이나 그 하위 타입을 쓰는게 일반적으로 최선
- Arrays 역시 asList와 Stream.of 메서드로 손쉽게 반복문과 Stream을 지원할 수 있음

> 반환받는 입장에서 선택지가 더 많은 Collection이 사용성 측면에서 더 낫다는 내용
