### ISSUE TITLE
아이템 49. 매개변수가 유효한지 검사하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#49]

**Comment by duckcalf** [comment]
- 매개변수의 유효성 체크는 함수의 몸체가 시작하기 전에 빨리 체크하는게 좋다.

매개변수 체크를 제대로 못하면..
1. 매서드가 수행되는 중간에 모호한 에러가 발생할 수 있다.
2. 메서드가 수행되고, 잘못된 결과가 반환된다.
3. 메서드는 잘 수행되었지만, 다른 객체의 상태를 변경하여 미래에 알 수 없는 시점에서 오류가 발생할 수 있다.
-> 매개별수 검사에 실패하면 실패 원자성(#76)을 어기는 결과가 나올 수 있다.

pulbic과 protected메서드는 매개변수 값이 잘못됐을때 던지는 예외를 문서화 해야 한다. (@throws를 사용하자. #74)
보통은 IllegalArgumentException, IndexOutOfBoundsException, NullPointerException 중 하나가 될 것이다. (#72)

자바7에 추가된 Java.util.Objects.requireNonNull 메서드는 유연하고 사용하기도 편하니, 더 이상 null 검사를 수동으로 하지 않아도 된다. 원하는 예외 메시지도 지정할 수 있고, 입력을 그대로 반환하므로 값을 사용하는 동시에 null검사를 수행할 수 있다.
```java
if(strategy == null) {
   throw new NullPointException("전략 값이 null 입니다.");
}
this.strategy = strategy;

this.strategy = Objects.requireNonNull(strategy, "전략")
```

자바9에서는 Objects에 범위 검사 기능도 더해졌다. checkFromIndexSize, chekcFromToIndex, checkIndex라는 메서드들인데, null 검사 메서드만큼 유연하지는 않다. 예외 메시지를 지정할 수 없고, 리스트와 배열 전용으로 설계됐다. 또한 닫힌범위는 다루지 못한다.


공개되지 않은 메서드라면 패키지 제작자인 여러분이 메서드가 호출되는 상황을 통제할 수 있다. 이런 경우, assert를 사용해 매개변수 유효성을 검증할 수 있다.

```java
private static void sort(long a[], int offset, int length) {
  assert a != null;
  assert offset >= 0 && offset <= a.length;
  assert length >= 0 && length <= a.length - offset;
  ... 할일들..
}
```
assert 문이 일반적인 유효성 검사와 다른점들..
1. 실패하면 AssertionError을 던진다.
2. 런타임에 아무런 효과도, 아무런 성능 저하도 없다 (-ea 혹은 --enableassertions 플래그로 런타임에도 검증 가능)

나중에 쓰려고 저장하는 경우에, null체크를 하지 않으면, 추후에 사용할때 어디서 해당 객체가 왔는지 모를 수 있음으로 주의하여야 한다.


매개변수 유효성 검사가 필요없는 경우.
1. 유효성 검사 비용이 지나치게 많이 들어갈 때
2. 계산 과정에서 암묵적으로 검사가 수행될때. (Collections.sort(List)는 아이템들이 상호비교가 불가능하면, ClassCastException을 던지게 된다. 이걸 굳이 미리 검사할 필요가 없다.)
하지만, 암묵적 검사를 수행하다가 실패 원자성(#76)을 해칠 수 있으니, 주의하자.


때로는, 실제 발생하는 예외와 API 문서에서 던지기로 하는 예외가 다를 경우가 발생할 수 있다. 이런 경우에는 예외번역 관용구(#73)를 사용하도록 하자.

**Comment by madplay** [comment]
- 와우 좋네요.
```java
String s = null;
s = Objects.requireNonNullElse(s, "123");
```
