### ISSUE TITLE
아이템 5. 자원을 직접 명시하지 말고 의존 객체 주입을 사용하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#5]

**Comment by enochyeon** [comment]
# 자원을 사용하는 방식

## 정적 유틸리티 클래스 (#4)

#### 코드 5-1 정적 유틸리티를 잘못 사용한 예 - 유연하지 않고 테스트하기 어렵다.
```java
public class SpellChecker {
  private static final Lexicon dictionary ...; // 정적 자원

  private SpellChekcer() {} // 객체 생성 방지

  public static boolean isValid(String word) { ... }
  public static List<String> suggestions(String typo) { ... }
```

## 싱클턴 (#3)

#### 코드 5-2 싱글턴을 잘못 하용한 예 - 유연하지 않고 테스트하기 어렵다.
```java
public class SpellChecker {
  private final Lexicon dictionary ...;

  private SpellChekcer(...) {}
  public static SpellChecker INSTANCE = new SpellCHecker(...); // 싱글턴 자원

  public boolean isValid(String word) { ... }
  public List<String> suggestions(String typo) { ... }
```

# 개선

## 의존성 주입

* 자원을 단 하나만 사용한다는 것은 훌류하지 않음. => 향후 확대도 고려해서 유연한 구조로 만들자는 의미
* 사용하는 자원에 따라 동작이 달라지는 클래스에는 적정 유틸리티 클래스나 싱글턴 방식이 적합하지 않다.
* 인스턴스를 생성할 때 생성자에 필요한 자원을 넘겨주는 방식

#### 코드 5-3 의존성 객체 주입은 유연성과 테스트 용이성을 높여준다.
```java
public class SpellChecker {
  private final Lexicon dictionary ...;

  public SpellChekcer(Lexicon dictionary) { // 생성된 자원
    this.dictionary = Objects.requireNonNul(dictionary);
  }

  public static boolean isValid(String word) { ... }
  public static List<String> suggestions(String typo) { ... }
```

## 장점
* 불변(#17) 보장
* 정적 팩터리(#1), 빌더(#2)에 똑같이 응용 가능

### 발전(변형)
* 생성자에 자원 팩터리 전달
  * [팩터리 메서드 패턴](https://ko.wikipedia.org/wiki/%ED%8C%A9%ED%86%A0%EB%A6%AC_%EB%A9%94%EC%84%9C%EB%93%9C_%ED%8C%A8%ED%84%B4)으로 구현
  * 자바8의 Supplier<T> 인터페이스 (#31)
```java
Mosaic create(Supplier<? extends Tile> tileFactory) { ... }
```

## 단점
* 의존성이 많으면 어지럽다.
  * 대안 : 프레임워크 사용(Dagger, Guice, Spring)
