### ISSUE TITLE
아이템 51. 메서드 시그니처를 신중히 설계하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#51]

**Comment by gaepury** [comment]
## 메서드 이름을 신중히 짓자.
- 표준 명명 규칙에 따라서 짓자.(자바 라이브러리 API 가이드를 참조하자)
- 같은 패키지에 속한 다른 이름들과 일관되게 짓자.

## 편의 메서드를 너무 많이 만들지 말자.
- 메서드가 너무 많은 클래스(인터페이스)는 익히고, 사용하고, 문서화하고, 테스트하고, 유지보수하기 어렵다.

## 매개변수 목록은 짧게 유지하자.
- 파라미터는 4개 이하로 만들자.

### 매개 변수를 줄이는 방법들
1. 여러 메서드로 쪼갠다.
   - getLastIndexFromSubList: List의 특정 요서들(subList) 중, 해당 요소의 마지막 인덱스(lastIndex)를 구하기 위해서는 3개의 매개변수 필요.
      - ![image](https://user-images.githubusercontent.com/20143765/54006834-564e7300-41a2-11e9-92d1-05245066caff.png)
   - subList와 lastIndexOf 메서드를 조합하여 사용
      - ![image](https://user-images.githubusercontent.com/20143765/54006848-6c5c3380-41a2-11e9-8a7b-6ae57965e2f6.png)


2. 매개변수 그룹들을 보존하는 도우미(Helper) 클래스를 만든다.
   - 사용전
 ![image](https://user-images.githubusercontent.com/20143765/54006564-28b4fa00-41a1-11e9-8454-22778c37af67.png)
   - 사용후
![image](https://user-images.githubusercontent.com/20143765/54006577-35d1e900-41a1-11e9-83b6-aae45ee0b2fe.png)


3. 빌더패턴을 사용한다
   - #2 (생성자에 매개변수가 많다면 빌더를 고려하라)

## 파라미터의 타입으로는 클래스보다 인터페이스가 낫다.
- 구체적으로 HashMap, HashSet이 아니라 Map, Set 인터페이스로 받는 것이 더 유연하다는 얘기다.
   - Map, Set으로 받게 되면 Map,Set을 구현한 다른 클래스(TreeMap, TreeSet)도 파라미터로 받을수 있다.

## boolean 보다는 원소 2개짜리 enum이 낫다.
- enum을 쓰게되면 코드를 읽고 쓰는게 더 용이하다.
### 예시)
- Live타입인지 아닌지에 따라 Player를 설정하는 로직이 다른 메서드
![image](https://user-images.githubusercontent.com/20143765/54006375-6c5b3400-41a0-11e9-841a-75d8f1c449af.png)
   - 타입이 늘어나게 된다면 boolean 매개 변수를 추가해야됨
- 이를 Enum으로 구현한다면, 아래와 같이 하나의 매개 변수로 구현이 가능하다. 
![image](https://user-images.githubusercontent.com/20143765/54006382-73824200-41a0-11e9-8fb2-c78b3b0d9f52.png)
