### ISSUE TITLE
아이템 55. 옵셔널 반환은 신중히 하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#55]

**Comment by seryang** [comment]
## 메서드가 특정 조건에서 값을 반환할 수 없을 때
- 총 2가지 (자바 8 이전)
   - 예외
   - null 반환
- 두 방법의 허점?
   - 예외의 경우 -> 진짜 예외적인 상황에서만 사용해야 한다 #69
   - null의 경우 -> NullPointerException 발생 위험 (null 처리 코드 추가 필요)

> 예를 들면.. 
```java
school.getClassRoom().getTeacher().getSubject().getSubjectName();
````

- 학교, 교실, 선생님, 과목이라는 클래스가 있을 때, 이 학교의 교실의 선생님의 과목을 반환하는 코드를 작성하면 if 지옥을 만남

```java
if(school != null) {
    ClassRoom classRoom = school.getClassRoom();
    if(classRoom != null) {
        Teacher teacher = classRoom.getTeacher();
        if(teacher != null) {
            Subject subject = teacher.getSubject();
            if(subject != null) {
                String subjectName = subject.getSubjectName();
                return subjectName;
            }
        }
    }
}
return null;
```
- 자바 8로 올라가면서 생긴 새로운 선택지, Optional<T>

## Optional이란?
- 값이 있을 수도 있고 없을 수도 있는 객체
- Optional은 원소를 최대 1개 가질 수 있는 불변 Collection
- 자바 8 이전의 코드보다 null-safe한 로직을 처리
- Optional을 반환하여 좀 더 로직을 유연하게 작성

> 55-1. 컬렉션에서 최댓값을 구한다(컬렉션이 비었으면 예외를 던진다)

```JAVA
    public static <E extends Comparable<E>> E max(Collection<E> c) {
        if (c.isEmpty())
            throw new IllegalArgumentException("빈 컬렉션");

        E result = null;
        for (E e : c)
            if (result == null || e.compareTo(result) > 0)
                result = Objects.requireNonNull(e);

        return result;
    }

    public static void main(String[] args) {
        List<String> words = Arrays.asList(args);
        System.out.println(max(words));
    }
```

> 결과

```java
Exception in thread "main" java.lang.IllegalArgumentException: 빈 컬렉션
	at item55.Main.max(Main.java:10)
	at item55.Main.main(Main.java:23)
```

> 55-2. 컬렉션에서 최댓값을 구해 Optional<E>로 반환

```JAVA
    public static <E extends Comparable<E>> Optional<E> max(Collection<E> c) {
        if (c.isEmpty())
            return Optional.empty();  // 빈 옵셔널

        E result = null;
        for (E e : c)
            if (result == null || e.compareTo(result) > 0)
                result = Objects.requireNonNull(e);

        return Optional.of(result);  // 값이 든 옵셔널
    }

    public static void main(String[] args) {
        List<String> words = Arrays.asList(args);
        System.out.println(max(words));
    }
```

> 결과

```java
Optional.empty
```

- Optional.of(value)에 null이 들어가면 NullPointerException을 던지니 주의
   - null 값도 허용하는 옵셔널을 만들려면 Optional.ofNullable(value) 사용
- 옵셔널을 반환하는 메서드에서는 절대 null을 반환하지 말것
   - 옵셔널을 도입한 취지를 완전히 무시하는 행위
- 스트림의 종단 연산 중 상당수가 옵셔널을 반환

> 55-3. max를 스트림 버전으로 다시 작성

```java
public static <E extends Comparable<E>> Optional<E> max(Collection<E> c) {
      return c.stream().max(Comparator.naturalOrder());
}
```

> 맨 처음 Sample 코드를 Optional로 수정한다면 아래와 같음

```java
// Before
if(school != null) {
    ClassRoom classRoom = school.getClassRoom();
    if(classRoom != null) {
        Teacher teacher = classRoom.getTeacher();
        if(teacher != null) {
            Subject subject = teacher.getSubject();
            if(subject != null) {
                String subjectName = subject.getSubjectName();
                return subjectName;
            }
        }
    }
}
return null;

// After
Optional.ofNullable(school).map(School::getClassRoom)    //Optional<School>
                           .map(ClassRoom::getTeacher)   //Optional<ClassRoom>
                           .map(Teacher::getSubject)     //Optional<Teacher>
                           .map(Subject::getSubjectName) //Optional<Subject>
                           .orElse(null);
```

- map 메서드에서 null인 경우 empty Optional을 반환하기 때문에 NPE가 발생하지 않음
- 최후에 orElse 구문에서 Optional 내부의 값이 null인 경우 파라미터로 들어간 null을 반환하기 때문에 NPE에 안전

## null을 반환하거나 예외를 던지는 대신 옵셔널 반환을 선택해야 하는 기준
>  옵셔널은 검사 예외와 취지가 비슷하다 #71 
- 반환값이 없을 수도 있음을 API 사용자에게 명확히 알려준다.
   - 비검사 예외를 던지거나 null을 반환한다면 API 사용자는 그 사실을 인지하지 못함 (런타임에서 예상치 못한 장애)
   - 검사 예외(checked Exception)를 던지면 클라이언트에서는 반드시 이에 대처하는 코드(try-catch 예외 처리)를 작성해넣음

- 옵셔널은 비슷하게, 메서드가 옵셔널을 반환한다면 클라이언트는 값을 받지 못했을때 취할 행동을 선택해야 함
1. 기본값 설정
```java
String lastWordInLexicon = max(words).orElse("단어 없음...");
````
  - 실제로 예외를 던진 것이 아니라, empty Optional이 리턴되기 때문에 예외 생성 비용이 들지 않음

2. 원하는 예외를 던질 수 있다.
```java
Toy myToy = max(toys).orElseThrow(TemperTantrumException::new);
````
  - 값이 없는 경우 원하는 예외를 던질 수 있다.

3.  항상 값이 채워져 있는 경우
```java
Element lastNobleGas = max(Elements.NOBLE_GASES).get();
````
   - 옵셔널에 항상 값이 채워져 있다고 확신할때 사용
    - 잘못 판단한 것이라면 NoSuchElementException 발생

4. 기본값을 설정하는 비용이 큰 경우 
```java
Connection connection = getConnection(datasource).orElseGet(() -> getLocalConnection());
```
  - 기본값을 설정하는 비용이 아주 커서 부담이 되는 경우 (`Supplier<T>`를 인수로 받는) orElseGet을 사용하면,
값이 처음 필요할 때 Supplier를 사용해 생성하므로 초기 생성비용을 낮출 수 있음

## [참고] Optional 메서드 정리
- Optional.empty()
   - 내부 값이 비어있는 Optional 객체 반환
- Optional.of(T value)
   - 내부 값이 value인 Optional 객체 반환
   - 만약 value가 null인 경우 NullPointerException 발생
- Optional.ofNullable(T value)
   - 가장 자주 쓰이는 Optional 생성 방법
   - value가 null이면, empty Optional을 반환하고, 값이 있으면 Optional.of로 생성
- T get()
   - Optional 내의 값을 반환
   - 만약 Optional 내부 값이 null인 경우 NoSuchElementException 발생
- boolean isPresent()
   - Optional 내부 값이 null이면 false, 있으면 true
- boolean isEmpty()
   - Optional 내부의 값이 null이면 true, 있으면 false
   - isPresent() 메서드의 반대
- void ifPresent(Consumer<? super T> consumer)
   - Optional 내부의 값이 있는 경우 consumer 함수를 실행
-` Optional<T> filter(Predicate<T> predicate)`
   - Optional에 filter 조건을 걸어 조건에 맞을 때만 Optional 내부 값이 있음
   - 조건이 맞지 않으면 Optional.empty를 리턴
- `Optional<U> map(Funtion<? super T, ? extends U> f)`
   - Optional 내부의 값을 Function을 통해 가공
- T orElse(T other)
   - Optional 내부의 값이 있는 경우 그 값을 반환
   - Optional 내부의 값이 null인 경우 other을 반환
- `T orElseGet(Supplier<? extends T> supplier)`
   - Optional 내부의 값이 있는 경우 그 값을 반환
   - Optional 내부의 값이 null인 경우 supplier을 실행한 값을 반환
- T orElseThrow()
   - Optional 내부의 값이 있는 경우 그 값을 반환
   - Optional 내부의 값이 null인 경우 NoSuchElementException 발생
- `T orElseThrow(Supplier<? extends X> exceptionSupplier)`
   - Optional 내부의 값이 있는 경우 그 값을 반환
   - Optional 내부의 값이 null인 경우 exceptionSupplier을 실행하여 Exception 발생

## Optional 안티 패턴
1. 컬렉션, 스트림, 배열, 옵셔널 같은 컨테이너 타입은 옵셔널로 감싸지 말것
    - 빈 `Optional<List<T>>`를 반환하기 보다는 빈 List<T>를 반환하는 것이 좋음 #54 
    - 빈 컨테이너를 그대로 반환하면 클라이언트에 옵셔널 처리 코드를 넣지 않아도 됨

2. Optional을 Map의 키나 값으로 사용하지 말자
    - 만약 Optional을 Map에서 사용한다면 모호한 상황이 발생함
        - Key 자체가 없는 경우
        - Key는 있지만, 속이 빈 Optional인 경우
        - 쓸데없이 복잡도만 높아지게 되고 전혀 쓸모없는 짓이니 사용하지 말자.
    - 일반화 하자면, Optional은 Collection의 키, 값, 원소나 배열의 원소로 사용하는게 적절한 상황은 거의 없음

## 정리
 - 값을 반환하지 못하거나 반환값이 없을 가능성이 있는 메서드라면 옵셔널 사용해보자
 - 하지만, 옵셔널 반환에는 성능 저하가 뒤따른다
 - 성능에 민감한 메서드라면 null을 반환하거나 예외를 던지는 편이 낫다
 - 옵셔널을 반환값 이외의 용도로 쓰는 경우는 매우 드물다
