### ISSUE TITLE
아이템 56. 공개된 API 요소에는 항상 문서화 주석을 작성하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#56]

**Comment by iknowchang** [comment]
- 자바독(Javadoc) : 소스코드 문서화 주석(doc comment)을 API문서로 변환해줌
- 공개된 모든 클래스, 인터페이스, 메서드, 필드 선언에 문서화 주석을 달아야한다.
- 해당 메서드와 클라이언트 사이 규약을 명료화
	- 상속용이 아니라면, how가 아닌 what을 기술
	- 메소드 호출을 위한 전제조건(precondition)을 모두 나열
		- 일반적으로 @throws 태그로 암시적 기술
		- @param으로 매개 변수 기술
	- 수행된 후의 사후조건(postcondition)을 모두 나열
	- 부작용 : 시스템 상태에 어떤 변화가 있는지. ( ex-background thread 시작시킴)
- 작성 가이드
	- 일반 가이드
		- 가독성 좋게 작성한다.  ` {@literal |r| < 1 } ` VS.  `|r|  {@literal < } 1  `
	- @param
		- 모든 매개변수
		- 관례상 명사구로 작성
		- 관례상 마침표 없이 작성
	- @return
		- void가 아니라면 작성, 서로 표준의 정의에 의해 메소드 설명과 같으면 생략 가능
		- 관례상 명사구로 작성
		- 관례상 마침표 없이 작성
	- @throws
		- 발생할 가능성이 있는 모든 예외
		- 관례상 마침표 없이 작성
	- @code
		- 코드용 폰트로 렌더링된다. 
		- HTML 요소 무시한다.
	- this 문구
		- 호출된 메서드 객체
	- HTML tag를 이용해 작성 가능
	- @implSpec ( p335)
		- 상속용 설계시 작성
		- super 키워드로 호출시 동작 설명
		- javadoc 명령줄에 명시해야 동작한다.
	- @literal
		- < > & 등 HTML 메타 문자 포함하기 위해 사용
	- 첫번째 문장 ( = 요소 요약 설명)
		- 요소 요약 설명으로 간주
		- 반드시 기능을 고유하게 작성
		- 한 클래스 내에 요약 설명이 똑같은 멤버가 둘 이상이면 안된다. ( 혼란)
		- “.”까지를 설명으로 판단한다. “Mrs.” 등은 @literal로 감싸준다. 
		- JAVA 10부터는 @summary 사용하면 된다. 
		- method, constructor 요약설명
			- 동작을 설명하는 동사어구로 작성
			- 설명은 3인칭 문장으로 작성
				- return the number (X)
				- returns th number (O)
		- class, interface, field 설명
			- 명사절로 작성 
	- @index
		- Java9부터 검색 가능해짐
		- 중요한 용어 @index 로 추가하여 추가 색인 가능
	- 제네릭 타입은 모든 타입 매개변수에 주석을 달아준다. (P339 예제)
	- 열거형 문서화 할때 숭수들도 주석 달아준다. 
	- 애너테이션 타입 문서화 할 떄는 멤버들도 모두 주석 달아준다. 
	- package 설명 문서 주석은 
		- package-info.java 파일에 작성
	- 모듈 시스템 문서 (JAVA9 부터)
		- module-info.java 파일에 작성
	- 쓰레드 안전 수준을 반드시 포함한다. 
	- 직렬화 할 수 있는 클래스라면 직렬화 형태도 기술
	- method 주석은 상속된다. 없으면 상위 class를 참고한다, 하지만, interface 주석이 더 우선순위가 높다. 
	- 전반적인 아키텍쳐 설명 문서가 따로 있다면 그 문서 링크를 제공하는 주석 작성

**Comment by madplay** [comment]
## 인텔리제이에서 javadoc 만드는 방법
### Tools 메뉴 > Generate JavaDoc...
![image](https://user-images.githubusercontent.com/8638571/57903131-a2571b80-78a7-11e9-9a5b-fe40801e39df.png)


### 만들 대상 프로젝트와 아웃풋 디렉터리 선택
- 파일이 많이 만들어지니까 바탕화면에 하면 화면 꽉찰 수 있으니 주의
- 옵션은 적절히 변경해서!
![image](https://user-images.githubusercontent.com/8638571/57903202-f6fa9680-78a7-11e9-9095-45b4f1ade2da.png)

### 결과물은 HTML로 나옵니다.
![image](https://user-images.githubusercontent.com/8638571/57903411-dbdc5680-78a8-11e9-988e-43802c22adc5.png)

### 인덱스
![image](https://user-images.githubusercontent.com/8638571/57903468-265dd300-78a9-11e9-8264-69ec936a7096.png)
