### ISSUE TITLE
아이템 57. 지역변수의 범위를 최소화하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#57]

**Comment by duckcalf** [comment]
### 지역변수는 사용할때 선언하고, 초기화 하자
- 옛날 언어의 습관때문에 함수의 머리부분에서 선언하는 경우가 있음. 자바는 어디에서 선언해도 되므로 쓸때 선언하자.
- 선언과 동시에 초기화를 하자. 그래야 안헷갈림.. 혹시 초기화를 아직 할 수 없다면, 초기화 할 수 있을때 선언하자.
 - try-catch문은 예외, 선언은 try밖에서 하지만, 초기화는 try안에서 해야 한다.

### 반복문을 쓸때는 while보다는 for문을 쓰자
- 권장 문법
```java
for (Element e : c) {
   ... // e로 뭔가를 한다.
}
```
- 반복자로 뭔가를 해야하는 경우
```java
for (Iterator<Element> i = c.iterator(); i.hasNext(); ) {
   Element e = i.next();
   ... // e와 i로 뭔가를 한다.
}
```
- while을 사용하면, scope 밖으로 필요없는 변수가 선언된다.
```java
Iterator<Element> i = c.iterator();
while (i.hasNext()) {
  doSomething(i.next());
}
...
Iterator<Element> i2 = c.iterator();
while (i.hasNext()) {  // 복붙하다가 발생한 버그!
  doSomething(i2.next());
}
```
- for문은 while문보다 짧아서 가독성이 좋음
```java
for (int i=0, n=expensiveComputation(); i < n; i++) {
   ...
}
// vs.
int i=0, n = excepsiveComputation();
while ( i < n) {
   ...
   i++;
}
```

### 가능한 메서드를 작게 유지하고 한 가지 기능에 집중하면 지역변수의 범위를 최소화 할 수 있음
