### ISSUE TITLE
아이템 59. 라이브러리를 익히고 사용하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#59]

**Comment by gaepury** [comment]
### 1. 표준 라이브러리를 사용하면 좋은점
   - 그 코드를 작성한 전문가의 지식과 이 라이브러리를 앞서 사용한 다른 개발자의 경험, 노하우 문서까지 활용할 수 있다. 
      - 책에서 예제로 든 Random보다는 jdk 1.7부터 나온 ThreadLocalRandom을 추천, Random은 멀티 스레드에서 사용할 경우 Seed 값이 겹치는 경우가 발생할 수 있으나, ThreadLocalRandom은 안전하다.)
      - 포크-조인 풀이나 병렬 스트림에서는 SplittableRandom을 추천
   - 핵심 비즈니스 로직 외에 들이는 시간이 줄어든다.
   - 따로 노력하지 않아도 성능이 지속적으로 개선된다.(업계 표준 벤처마크를 사용해 성능을 확인)
   - 기능이 점점 많아진다. (커뮤니티에서 요구가 나오고 논의되면 다음 릴리즈에 기능이 추가되곤 한다)
   - 많은 사람들에게 낯익은 코드가 되기 때문에 유지보수성과 재활용성이 좋아진다.

### 2. 메이저 릴리스마다 주목할 만한 수많은 기능이 라이브러리 추가된다.
```
public class Curl {
    public static void main(String[] args) throws IOException {
        try (InputStream in = new URL(args[0]).openStream()) {
            in.transferTo(System.out);
        }
    }
}
```
   - transferTo 메서드를 이용해 URL의 내용 가져오기 - (자바 9부터 가능)
      - 매우 심플하다

### 3. 자바 개발자라면 java.lang, java.util, java.io와 그 하위패키지들에는 익숙해져라.
   - 컬렉션 프레워크와 스트림 라이브러리(아이템 45~48), java.util.concurrent.. 등

### 4. 서드파티 라이브러리 
- 원하는 기능이 없다면 서드파티 라이브러리들을 사용해보자.
- 서드파티 라이브러리 종류들
   - apache commons : StringUtils, DateUtils, DateFormatUtils, ObjectUtils...
   - google guava : 컬렉션(ImmutableMap, ImmutableList), 캐싱(caffeine), 문자열 처리 등 구글에서 만든 자바 라이브러리들
   - jackson
