### ISSUE TITLE
아이템 60. 정확한 답이 필요하다면 FLOAT와 DOUBLE은 피하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#60]

**Comment by nypark425** [comment]
### float와 double
- 과학과 공학 계산용으로 설계되었습니다.
- [이진 부동 소수점](https://ko.wikipedia.org/wiki/%EB%B6%80%EB%8F%99%EC%86%8C%EC%88%98%EC%A0%90)연산에 쓰이며,
- 넓은 범위의 수를 빠르게 정밀한 '*근사치*'로 계산하도록 설계되었습니다.
    - 즉, **금융 관련 계산에는 알맞지 않습니다.**
    - 0.1 혹은 10의 음의 거듭제곱 수(10^(-1), 10^(-2), ...) 등을 표현할 수 없기 때문입니다.
```java
System.out.println(1.03 - 0.42);
// expected: 0.61
// actual: 0.6100000000000001

System.out.println(1.00 - 9 * 0.10);
// expected: 0.10
// actual: 0.09999999999999998	
```
- 1달러가 있고, 선반에는 10센트, 20센트, 30센트... 1달러 짜리의 사탕이 있습니다.
```java
double funds = 1.00;
int itemsBought = 0;
for (double price = 0.10; funds >= price; price += 0.10) {
	funds -= price;
	itemsBought++;
}
System.out.println(itemsBought + "개 구입");
System.out.println("잔돈(달러): " + funds);
```
```
// 결과
3개 구입
잔돈(달러): 0.3999999999999999
```

### 정확한 계산이 필요할 땐 BigDemical, int 혹은 long을 사용하자.
- 먼저, 앞의 코드에서 ```double``` -> ```BigDemical```로 교체해볼까요?
```java
final BigDecimal TEN_CENTS = new BigDecimal(".10");
int itemsBought = 0;
BigDecimal funds = new BigDecimal("1.00");
for (BigDecimal price = TEN_CENTS; funds.compareTo(price) >= 0; price = price.add(TEN_CENTS)) {
	funds = funds.subtract(price);
	itemsBought++;
}
System.out.println(itemsBought + "개 구입");
System.out.println("잔돈(달러): " + funds);
```
```
// 결과
4개 구입
잔돈(달러): 0.00
```
- 하지만 BigDemical에는 단점이 있습니다.
    1. primitive 타입보다 사용하기 훨씬 불편합니다.
    2. 훨씬 느립니다.
- 대신 int나 long 타입을 사용한다면?
    - 다룰 수 있는 값의 크기가 제한되고, 소숫점을 직접 관리해야 합니다.
- int를 사용해봅시다. 단, 달러 대신 센트로 계산!
```java
// 달러 대신 센트로 계산
int itemsBought = 0;
int funds = 100;
for (int price = 10; funds >= price; price += 10) {
	funds -= price;
	itemsBought ++;
}
System.out.println(itemsBought + "개 구입");
System.out.println("잔돈(센트): " + funds);
```
```
// 결과
4개 구입
잔돈(센트): 0
```

### 정리
- 정확한 계산이 필요하다면 float나 double은 피합시다.
- 소숫점 처리는 시스템에 맡기고, 코딩 시의 불편함과 성능 저하를 신경쓰지 않겠다면 ```BigDemical```를 사용해도 좋아요.
    - 아니라면 ```int```나 ```long```을 사용하면 됩니다.
        - 9자리 십진수: ```int```
        - 18자리 십진수: ```long```
        - 18자리를 넘어간다면 어쩔 수 없이 ```BigDemical```
