### ISSUE TITLE
아이템 61. 박싱된 기본 타입보다는 기본 타입을 사용하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#61]

**Comment by enochyeon** [comment]
## 개요
### 데이터 타입
* 기본 : `int`, `double`, `boolean`, ...
* 참조 : `String`, `List`, ,,,
  * 박싱(된 기본) : `Integer`, `Double`, `Boolean`, ...
### 사용
* 오토박싱/오토언박싱 덕분에 구분 없이 사용할 수 있음(#6)
### 기본/박싱의 차이
특성 | 기본타입 | 박싱된 기본타입
--|--|--
식별성 | 값만 있음 | 값, 식별성(identity) 속성도 있음
유효성 | 항상 | null이 될 수 있음
시간,메모리 | 효율적 | 상대적으로 비효율적

## 문제 사례 1
#### 코드 61-1 잘못 구현된 비교자 - 문제를 찾아보자!
```java
Comparator<Integer> naturalOrder = (i, j) -> (i < j) ? -1 : (i == j ? 0 : 1);

// (new Integer(42), new Integer(42)) 입력하면?
```
* 박싱된 기본 타입에 `==` 연산자를 사용하면 오류 발생

#### 코드 61-2 문제를 수정한 비교자
```java
Comparator<Integer> naturalOrder = (iBoxed, jBoxed) -> {
  int i = iBoxed, j = jBoxed; // 오토박싱
  return i < j ? -1 : (i == j ? 0 : 1);
};
```

## 문제 사례 2
#### 코드 61-3 기이하게 동작하는 프로그램 - 결과를 맞혀보자!
```java
public class Unbelievable {
  static Integer i;

  public static void main(String[] args) {
  if (i == 42)
    System.out.println("믿을 수 없군!");
  }
}
```
* 기본 타입과 박싱된 기본 타입을 혼용한 연산에서는 **박싱된 기본 타입의 박싱이 자동으로 풀림**

## 문제 사례 3
#### 코드 61-4 끔찍이 느리다! 객체가 만들어지는 위치를 찾았는가? - 코드 6-3(#6)과 같음
```java
private static long sum() {
    Long sum = 0L;
    for (long i = 0 ; i <= Integer.MAX_VALUE ; i++) {
        sum += i;
    }
    
    return sum;
}
```
* 박싱과 언박싱인 반복해서 일어나 성능이 느려짐

## 정리
### 박싱된 기본 타입의 사용
1. 컬렉션의 원소, 키, 값
2. 매개변수화 타입이나 매개변수화 메서드([5장](https://github.com/NMP-Study/EffectiveJava/milestone/4))의 타입 매개변수로 사용
3. 리플렉션(#65) 메서드 호출 시

**Comment by madplay** [comment]
### int
```java
Comparator<Integer> naturalOrder = (i, j) -> (i < j) ? -1 : (i == j ? 0 : 1);
List<Integer> list = new ArrayList<>();
list.add(2);
list.add(2);
List<Integer> collect = list.stream().sorted(naturalOrder).collect(Collectors.toList());
System.out.println(collect);
```
![image](https://user-images.githubusercontent.com/8638571/57902983-e8f84600-78a6-11e9-8b60-03267f5c8910.png)


### Integer
```java
Comparator<Integer> naturalOrder = (i, j) -> (i < j) ? -1 : (i == j ? 0 : 1);
List<Integer> list = new ArrayList<>();
list.add(new Integer(2));
list.add(new Integer(2));
```
![image](https://user-images.githubusercontent.com/8638571/57903084-691eab80-78a7-11e9-81df-0d405c516c44.png)
