### ISSUE TITLE
아이템 62. 다른 타입이 적절하다면 문자열 사용을 피하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#62]

**Comment by fairsun** [comment]
### String
- 텍스트를 표현하도록 설계됐지만 의도하지 않은 용도로도 쓰이는 경향이 있다.

### 문자열은 다른 값 타입을 대신하기에 적합하지 않다. 
- 수치형 => int, float, BigInteger
- '예/아니오' => enum, boolean

기본 타입이든 참조 타입이튼 적절한 값 타입이 있다면 그것을 사용하고, 없다면 새로 하나 작성하라.

### String은 enum 타입을 대신하기에 적합하지 않다. 
- 상수를 열거할 때는 enum 타입이 월등히 낫다.(#34)

### String은 혼합 타입을 대신하기에 적합하지 않다. 
- ex> String compoundKye = className + "#" + i.next();
- className에 "#"이 포함된다면?? parsing error
- 느리고 귀찮고 오류 가능성이 커짐
- equals, toString, compareTo 메서드를 제공할 수 없고 String이 제공하는 기능에 의존해야 함.

=> 전용 클래스 선언 :  private 정적 멤버 클래스 (#24)

### String은 권한을 표현하기에 적합하지 않다. 

- String로 key를 사용하는 경우
~~~java
public class ThreadLocal {
    private ThreadLocal() {
    }

    public static void set(String key, Object value) {
        //...
    }

    public static Object get(String key) {
        //...
    }
}
~~~

- 문자열 대신 위조할 수 없는 키를 사용한다.
~~~java
public class ThreadLocal {
    private ThreadLocal() {
    }

    public static class Key {
        Key() {
        }
    }

    public static Key getKey() {
        return new Key();
    }

    public static void set(Key key, Object value) {
        //...
    }

    public static Object get(Key key) {
        //...
    }
}
~~~

- 중첩 클래스 Key -> ThreadLocal
- 타입 안정성을 보장하기 위해 Object를 제너릭으로 선언한다. (#29)
- java.lang.ThreadLocal과 비슷
~~~java
public final class ThreadLocal {
    private ThreadLocal() {
    }

    public static class Key {
        Key() {
        }
    }

    public static Key getKey() {
        return new Key();
    }

    public void set(Object value) {
        //...
    }

    public Object get() {
        //...
    }
}
~~~
