### ISSUE TITLE
아이템 63. 문자열 연결은 느리니 주의하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#63]

**Comment by seryang** [comment]
## 문자열 연결 연산자(+)는 편리합니다
- 여러 문자열을 하나로 합쳐주는 편리한 수단
- 하지만, 문자열 n개를 잇는 시간은 n^2에 비례한다. (성능 저하 발생)

```java
public String statement() {
   String result = "";
   for (int i = 0 ; i < numItems(); i++) {
         result += lineForItem(i);
   }
  return result;
}
```
- 품목이 많을 경우 이 메서드는 심각하게 느려짐

## String 객체는 한번 생성되면 할당된 메모리 공간이 변하지 않습니다
- `+` 는 기존 문자열에 새로운 문자열을 붙이는 것이 아니라, 새로운 String 객체를 만든 후, 새 String 객체에 연결된 문자열을 저장하고, 그 객체를 참조 
     - String 클래스 객체는 Heap 메모리 영역에 생성되는데, 한번 생성된 객체의 내부 내용을 변화시킬 수 없음 (문자열 불변 #17)
    - 문자열 연산이 많아질 때 계속해서 객체를 만드는 오버헤드가 발생
    - 기존 객체가 제거되면 GC가 회수(언제 제거될지 모름)

## 성능을 포기하고 싶지 않다면 String 대신 StringBuilder를 사용하자.
- StringBuilder는 String과 다르게 mutable(가변)
- 클래스를 한번만 만들고(new), 연산이 필요할 때 크기를 변경시켜서 문자열을 변경

## StringBuffer vs StringBuilder
- StringBuilder 동기화 지원 `x`  (Single Thread 상황에서 사용)
- StringBuffer 동기화 지원 `o` (Multi Thread 상황에서 사용)

```java
public final class StringBuffer {
     public synchronized StringBuffer append(String str) {
          super.append(str);
          return this;
     }
    ...
}

public final class StringBuilder {
     public StringBuilder append(String str) {
          super.append(str);
          return this;
     }
     ...
}
```

## 추가 
- JDK1.5이상부터 String에서 +연산으로 작성하더라도 StringBuilder로 컴파일하게 만들어 놓았음
     - 하지만, 여전히 String클래스의 객체 생성하는 부분이 동일함
- 단순히 성능으로 비교한다면, `StringBuilder > StringBuffer > String `
