### ISSUE TITLE
아이템 64. 객체는 인터페이스를 사용해 참조하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#64]

**Comment by iknowchang** [comment]
**적합한 인터페이스만 있다면 매개변수 뿐 아니라 반환값, 변수, 필드를 전부 인터페이스 타입으로 선언하라**
```
// 좋은 예
Set<Son> sonSet = new LinkedHashSet<>();
// 나쁜 예
LinkedHashSet <Son> sonSet = new LinkedHashSet<>();
```

* 장점
	* 나중에 구현 클래스 교체에 유연  ex) LinkedHashSet => HashSet
	* 쉬운 교체로 성능 향상 또는 신기능 기대 ex) HashMap => EnumMap 속도 빠르고 순회 순서 키순서 보장 => LinkedHashMap (EnumMap)이 열거 타입만 사용할 수 있다는 단점 보완.
* 주의
	* 구현체가 인터페이스 규약 외의 특별 기능이 있다면 주의 
		* ex) LinkedHashSet 의 순서 정책을 가정하고 사용했었다면 HashSet 으로 바꾸면 문제됨
* 적합한 인터페이스 없는 부류
	* 적합한 인터페이스가 없다면 당연히 클래스로 참조
		* String, BigInteger
	* 클래스 기반 작성 객체는 (보통 추상 클래스)기반 클래스 참조가 좋다. 
		* ex) OutputStream, java.io 하위
	* 특별 메서드 제공 객체
		* PriorityQueue는 (인터페이스에는 없는)comparator 메소드 제공
		* 가능하면 최소화
