### ISSUE TITLE
아이템 65. 리플렉션보다는 인터페이스를 사용하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#65]

**Comment by duckcalf** [comment]
### 리플렉션은 강력하지만, 단점이 있다.
- 컴파일타임 타입 검사가 주는 이점을 하나도 누릴 수 없다. (각종 런타임 오류가 발생할 수 있다)
- 리플렉션을 이용하면 코드가 지저분하고 장황해진다.
- 성능이 떨어진다. (필자의 실험으로 약 11배 느려진다고 함)

리플렉션을 써야할지 말아야할지 고민된다면, 쓰지 않아야 한다.

### 리플렉션은 아주 제한된 형태로만 사용해야 그 단점을 피하고 이점만 취할 수 있다.
사용해야 하는 상황 : 컴파일 타임에는 존재하지 않는 클래스를 사용해야만 하는 경우!
하지만, 이것도 인터페이스로 왠만하면 인터페이스로 쓰고, 생성시에만 리플렉션을 사용하자.

### 리플렉션이 필요한 경우
- 존재하지 않을 수도 있는 다른 클래스, 메서드, 필드등을 다룰때 적합하다.
- 외부의 다른 패키지를 사용하는 경우, 해당 메서드가 존재하는지(버젼에 따라 다를 수 있음으로) 확인하고 사용할 수 있다.
