### ISSUE TITLE
아이템 67. 최적화는 신중히 하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#67]

**Comment by gaepury** [comment]
### 최적화 격언 3개
> 1. 그 어떤 핑계보다 효율성이라는 이름 아래 행해진 컴퓨팅 죄악이 더 많다.(심지어 효율을 높이지도 못하면서)
> 2. 자그마한 효율성은 모두 잊자. 섣부른 최적화가 만악의 근원이다.
> 3. 다음 두 규칙을 따르라.  첫번째, 하지마라, 두번째, (전문가 한정) 아직 하지마라. 다시 말해 완전히 명백하고 해법을 찾을때까지는 하지마라.


### 1. 빠른 프로그램보다는 좋은 프로그램을 작성하라.
성능때문에 견고한 구조를 희생하지 말아야 한다. 빠른 프로그램보다는 좋은 프로그램이 좋다. 애초에 설계 단계에서 성능을 반드시 염두에 두어야 한다. 아키텍처의 결함이 성능을 제한하는 상황이라면 전체를 다시 작성하지 않고는 해결이 불가능하기 때문이다.

### 2. 성능을 제한하는 설계를 피하라.
- 완성 후 변경하기 어려운 설계 요소는 외부 컴포넌트, 시스템과의 소통 방식이다. (API, 프로토콜, 파일데이터 등). 이런 설계 요소들은 변경이 어렵거나 불가능할 수 있으며, 동시에 성능을 심각하게 제한할 수 있으므로 설계부터 성능을 염두에 두어야 한다.

### 3. API를 설계할 때 성능에 주는 영향을 고려하라. 
public 메소드에서 내부 데이터를 변경할 수 있게 만들면 불필요한 방어적 복사를 유발한다. 또한 컴포지션으로 해결할 수 있음에도 상속 방식으로 설계한 public클래스는 영원히 상위 클래스에 종속되고 성능까지 물려받는다.(더 빠른 구현체가 나오더라도 이용하지 못한다.)

### 4. 각각의 최적화 시도 전후로 성능을 측정하라. 
- 프로파일링 도구는 최적화 노력을 어디에 집중해야할지 도움을 준다. 
- 가장 먼저 어떤 알고리즘을 사용했는지 살펴보는게 도움이 된다.
