### ISSUE TITLE
아이템 68. 일반적으로 통용되는 명명 규칙을 따르라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#68]

**Comment by nypark425** [comment]
### 자바의 명명규칙
- [자바 언어 명세 Java Language Specification 6.1](https://docs.oracle.com/javase/specs/jls/se9/html/jls-6.html#jls-6.1)에 잘 기술되어있습니다.
- 크게 두 범주 : **철자, 문법**

## 1. 철자 규칙
- 패키지, 클래스, 인터페이스, 메서드, 필드, 타입 변수의 이름을 다룸
- 특별한 이유가 없다면 반드시 따라야 합니다.
    - 유지보수가 어려워지고, 의미를 오해하는 것을 방지하기 위함 

### 패키지, 모듈
- 각 요소를 점(.)으로 구분하여 계층적으로 : ```package java.util.function;```
- 요소들은 모두 소문자 알파벳 또는 숫자
- 외부에서도 사용될 패키지라면 조직의 인터넷 도메인 이름을 역순으로 : ```package com.naver.news.m.interfaces;```
- 각 요소는 일반적으로 8자 이하의 짧은 단어로
  - ```utilities``` 보다는 의미가 통하는 약어인 ```util```로

### 클래스, 인터페이스
- 하나 이상의 단어로 이루어짐
- Pascal Case : 각 단어의 첫번째 글자는 대문자로 : ```public interface ToIntBiFunction```
- max, min 등 널리 통용되는 줄임말이 아니라면 단어는 줄여쓰지 않도록
- 약자(줄임말, acronym)의 경우는?
    - 첫 글자만 대문자로 할지, 다 대문자로 할지는 논란..
    - 하지만 첫 글자만 대문자로 하는 쪽이 많다. (취향 차이일 듯 합니다.)
        - ```HttpUrl``` vs ```HTTPURL```

### 메서드, 필드
- Camel Case : 맨 첫 글자는 소문자이고, 나머지 단어의 첫글자는 대문자로 : ```public static <T> T requireNonNull(T obj)```
- 첫 단어가 약자라면 그 단어 전체는 소문자로
- 예외: **상수 필드**
    - 모든 글자는 대문자로
    - 단어 사이에는 언더바(_)로 구분 : ```private static final String SECTION_ID_NONE = "001";```

### 지역변수
- 약어를 써도 좋다!
    - 변수가 사용된 문맥에서 의미를 유추할 수 있기 때문 : ```for(int i=0; i<list.size(); i++)```

### 타입 매개변수
- 보통 한 문자로 표현
- ```T``` : 임의의 타입, Type
- ```E``` : 컬렉션 원소의 타입, Element
- ```K``` : 맵의 키, Key
- ```V``` : 맵의 값, Value
- ```X``` : 예외, eXecption
- ```R``` : 메서드의 반환 타입, Return
- ```T, U, V```, ```T1, T2, T3``` : 임의 타입의 시퀀스

## 2. 문법 규칙
### 객체를 생성할 수 있는 클래스, Enum 타입
- 보통 단수 명사 또는 명사구 : ```Thread, PriorityQueue, ChessPiece```

### 객체를 생성할 수 없는 클래스 (#4)
- 보통 복수형 명사 : ```Collectors, Collections```

### 인터페이스
- 클래스와 똑같이 : ```Collection, Comparator```
- able 또는 ible로 끝나는 형용사 : ```Runnable, Accessible```

### 어노테이션
- 큰 규칙 없이 명사, 동사, 형용사, 전치사가 두루 쓰임 : ```BindingAnnotation, Inject, Singleton```

### 메소드
- 동사나 동사구 : ```append, drawImage```
- boolean을 반환한다면 is나 has로 시작하고 명사/명사구/형용사로 끝난다. : ```isDigit, isEmpty, hasSiblings```
- boolean을 반환하지 않거나 인스턴스의 속성을 반환한다면 보통 명사/명사구/혹은 get으로 시작하는 동사구를 사용한다. : ```size, hashCode, getTime```
- 클래스가 한 속성의 getter와 setter를 모두 제공한다면 ```get~```, ```set~```이 좋다.

### 특별한 메소드들
- 타입을 바꿔서 다른 타입의 객체를 반환하는 역할을 한다면 ```to~``` : ```toString, toArray```
- 객체의 내용을 다른 뷰로 보여주는 메소드(#6)는 ```as~``` : ```asList```
- 객체의 값을 primitive 타입으로 반환한다면 ```~Value``` : ```intValue```
- 정적 팩터리라면 : ```from, of, valueOf, instance, getInstance, get~, new~```(#1)

### 필드
- 규칙이 덜 명확하고 덜 중요
- boolean 타입의 필드명은 보통 boolean 접근자 메소드에서 앞 단어를 뺀 형태 : ```initialized, composite```
- 다른 타입의 필드는 명사/명사구를 사용 : ```height, digits, bodyStyle```
- 지역변수 명은 비슷하지만 좀더 느슨하다.

### 정리하자면
- 표준 명명 규칙을 습관화하자.
- JLS 6.1, "오랫동안 따라온 규칙과 충돌한다면 그 규칙을 무조건 따라서는 안된다".
    - 즉, 상식이 이끄는대로 하자.
