### ISSUE TITLE
아이템 69. 예외는 진짜 예외 상황에만 사용하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#69]

**Comment by enochyeon** [comment]
## 예시

#### 코드 69-1 예외를 완전히 잘못 사용한 예 - 따라 하지 말 것!
```java
try {
  int i  0;
  while(true)
    range[i++].climb();
} catch (ArrayIndexOutOfBoundsException e) {
}
```
* 배열의 끝을 넘는 경우 무한루프를 중단하려는 의도. 이렇게 작성하면 안됨!(#67)
* 잘못 된 추론에 의한 구현. JVM 동작에 대한 이해 부족.
* 단점
  * 불명확한 코드
  * 성능 저하
  * 오동작 가능성 내포
  * 디버깅 불편함

#### 개선
```java
for (Mountain m : range)
  m.climb();
```
* 예외 검사보다 훨씬 빠름

## 요점
* 예외는 오직 예외 상황에서만 쓸 것.
* 일상적인 제어 흐름용으로 사용하지 말 것.
* API를 잘 설계하려면 예외를 사용할 일이 없게 하기.
* 예시
  * 상태 검사 메소드 제공
  * 빈 옵셔널(#55) 제공
  * null 같은 특정 값 반환
