### ISSUE TITLE
아이템 71. 필요 없는 검사 예외 사용은 피하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#71]

**Comment by seryang** [comment]
## 검사 예외를 제대로 활용하면 API와 프로그램의 질을 높인다
- 발생 문제를 프로그래머가 처리하여 안전성을 높임

## 하지만, 검사 예외를 과하게 사용하면 오히려 쓰기 불편한 API
- 어떤 메서드가 검사 예외를 던질 수 있다고 선언됐다면, 
    - 이를 호출하는 코드에서는 그 예외를 붙잡아 예외를 처리하거나 (catch)
    - 더 바깥으로 던져 문제를 전파 (throw new)
- 자바 8의 경우, 검사 예외를 던지는 메서드는 스트림 안에서 직접 사용할 수 없음 (#45 ~ #48)
- API 사용자에게 부담을 줌

## 비검사 예외 vs 검사 예외 중 어느 것을 선택?
- API를 제대로 사용해도 발생할 수 있는 예외이거나, 프로그래머가 의미 있는 조치를 취할 수 있는 경우라면 `검사 예외 ok`
- 하지만, 그 어디에도 해당하지 않는다면 비검사 예외를 사용하는게 좋음

``` java
} catch (TheCheckedException e) {
    throw new AssertionError(); // 일어날 수 없다!
}
```

```java
} catch (TheCheckedException e) {
     e.printStackTrace(); // 이런, 우리가 졌다.
     System.exit(1);
}
```

## 검사 예외를 회피하는 방법
1. 적절한 결과 타입을 담은 옵셔널 반환 (#55)
- 검사 예외를 던지는 대신 단순히 빈 옵셔널을 반환
- 단점이라면, 예외가 발생한 이유를 알려준느 부가 정보를 담을 수 없다는 것

2. 검사 예외를 던지는 메서드를 2개로 쪼개 비검사 예외로 바꿈

```java
/* 검사 예외를 던지는 메서드 - 리팩터링 전 */
try {
    obj.action(args);
} catch (TheCheckedException e) {
    ... // 예외 상황에 대처한다.
}
```

- actionPermitted() 메서드를 만들어, 예외가 던져질지 여부를 boolean 값으로 반환
```java
/* 검사 예외를 던지는 메서드 - 리팩터링 후 */
if (obj.actionPermitted(args)) {
    obj.action(args);
} else {
    ... // 예외 상황에 대처한다.
}
```
 
## 정리
- 꼭 필요한 곳에만 사용하면 검사 예외는 프로그램의 안전성을 높여준다.
- 남용하면 쓰기 고통스러운 API를 낳는다.
- API 호출자가 예외 상황에서 복구할 방법이 없다면 비검사 예외를 던지자.
- 복구가 가능하고 호출자가 그 처리를 해주길 바란다면? 
   - 우선 옵셔널을 반환해도 될지 고민하자
   - 옵셔널만으로는 상황 처리하기 충분한 정보를 제공할 수 없다면 검사 예외를 던지자
