### ISSUE TITLE
아이템 72. 표준 예외를 사용하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#72]

**Comment by iknowchang** [comment]
* 숙련된 프로그래머는 더 많은 코드를 재사용한다. 
* 충분한 수의 표준 예외 있음
* 장점
	* 다른 사람이 사용하기 읽기 쉽고 사용하기 편함
	* 메모리 사용량 줄어듬. 
* IllegalArgumentException
	* 호출자가 부절한 값을 넘길 때 
* IllegalStateException
	* 객체의 상태가 호출된 메소드를 수행하기 적절하지 않을때
	* 예) init 안된 상태인데 객체 사용하려할 때
* 관례상 arg에 다음 값이 들어오면..
	* null허용하지 않은데 arg에 null을 건네면 (IllegalArgumentException가 아닌 ) NullPointerException을 던진다. 
	* 허용 범위 넘는 값이면 IndexOutOfBoundsException
* ConcurrentModificationException
	* 단일 객체에서 사용하려고 설계했는데, 동시 여러 객체가 수정하려할 때
* UnsupportedOperationException
	* 클라이언트가 요청한 동작을 대상 객체가 지원하지 않을 때
	* 보통 구현하려는 interface의 모든 method를 구현하지 않았을 때 
* Exception, RuntimeException, Throwable, Error는 직접 재사용하지 말자
	* 추상 클래스로 생각
	* 여러 성격 예외를 포괄하므로 안정적 테스트 어려움
* 더많은 정보르 제공하고 싶다면 표준 예외를 확장해도 좋다. 
	* 단, 예외는 직렬화 할 수 있다는 점을 기억
* 예외 선택이 힘든 경우.
	* 예를 들어 integer 만큼 카드를 주는 mtehod에 남아있는 카드보다 많은 수의 요청이 들어오면?
		* IllegalArgumentException ? ( 인수 값이 너무 크다고 생각하면..) 
		* IllegalStateException ? ( 남은 카드 수가 너무 작다고 생각하면 ) 
		* 일반적인 규칙은? 인수 값이 무엇이든 어차피 실패라면 IllegalStateException
		* 그렇지 않으면 IllegalArgumentException
