### ISSUE TITLE
아이템 73. 추상화 수준에 맞는 예외를 던지라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#73]

**Comment by duckcalf** [comment]
## 상위 계층에서는 저수준 예외를 잡아 자신의 추상화 수준에 맞는 예외로 바꿔 던져야 한다.
- article.getJournalist()를 호출했는데, IndexOutOfBoundsException 이 나오면 당황스럽다.
- 저수준 예외를 클라이언트에서 처리하는 경우, 내부 로직을 변경했을때 대응하기가 어려워진다.

* 예외번역의 예시
```java
try {
    ... // 저수준 추상화를 이용한다.
} catch (LowerLevelException e) {
   // 추상화 수준에 맞게 번역한다.
   throw new HigherLevelException(...);
}
```
* 저수준의 예외가 디버깅에 도움되는 경우에는, 원인을 실어 보낸다.
```java
try {
    ... // 저수준 추상화를 이용한다.
} catch (LowerLevelException cause) {
   // 추상화 수준에 맞게 번역한다.
   throw new HigherLevelException(cause);
}
```

### 무턱대고 예외를 전파하는 것보다야 예외 번역이 우수한 방법이지만, 그렇다고 남용해도 곤란하다.
- 가능하다면 저수준 메서드가 반드시 성공하도록 하는게 좋다.
- 왠만하면 저수준에서 오류가 발생하지 않도록 파라미터등을 미리 검사하자. #49 
- 로깅을 하고, 예외를 먹는것도 도움이 될 수 있다.
