### ISSUE TITLE
아이템 75. 예외의 상세 메시지에 실패 관련 정보를 담으라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#75]

**Comment by gaepury** [comment]
#### - catch하지 않은 예외가 발생하면 시스템에서 자동으로 스택 추적(stack trace) 정보를 출력한다.
![image](https://user-images.githubusercontent.com/20143765/56374936-3a2cff80-623f-11e9-8ae7-00297d53c3c8.png)

#### - 이때 출력되는 문자열은 Throwable 클래스의 toString 메서드가 반환하는 정보(클래스 이름과 상세 메세지(detailMessage)가 결합된 형태)
![image](https://user-images.githubusercontent.com/20143765/56374829-094cca80-623f-11e9-8345-c24720500386.png)
   - Throwable Class

실패 순간을 포착하려면 발생한 예외에 관여된 모든 매개변수와 필드의 값을 실패 메시지에 담아야 한다.
- 주의할 점
   1. 실패 원인을 분석할 떄 도움이 되는 메세지를 담아야 한다.(관련 데이터를 모두 담아야 하지만 장황할 필요는 없다.)
   2. 보안과 관련한 정보는 포함시키지 말아야 한다.


아래처럼 IndexoutOfBoundsException의 상세 메시지는 범위의 최솟값과 최댓값, 그리고 그 범위를 벗어났다는 인덱스의 값을 담는걸 추천 
![image](https://user-images.githubusercontent.com/20143765/56375296-13bb9400-6240-11e9-82fc-345f6d207d96.png)
