### ISSUE TITLE
아이템 77. 예외를 무시하지 말라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#77]

**Comment by enochyeon** [comment]
## 요점
* 예외가 선언된 API 설계 의도를 무시하지 말자!
* 빈 catch를 사용하지 않도록. 보고 그냥 지나치지 않도록.
* 검사와 비검사 예외 모두 동일함.

## 예외
* `FileInputStream` 같은 것을 닫을 때는 조치할 게 없음. 그래도 로그라도 남기자.
