### ISSUE TITLE
아이템 8. FINALIZER와 CLEANER 사용을 피하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#8]

**Comment by iknowchang** [comment]
### 2가지 객체 소멸자
- finalizer
   - deprecate Object.finalize()
- cleaner
   - java.lang.ref.Cleaner
   - ex : https://www.logicbig.com/tutorials/core-java-tutorial/gc/ref-cleaner.html
### 주의
- 언제 실행될지 알 수 없습
- JAVA 버전, gabage collector 구현에 따라 제각각
- 느림, 쓰레드 우선순위 낮음
### Specification
- Implementing Finalization : [Chapter 12. Execution](https://docs.oracle.com/javase/specs/jls/se8/html/jls-12.html#jls-12.6)
	- method : protected method finalize
	- 언제, 어떤 thread에서 finalizer 실행할지 알 수 없음.
	- finalization 과정에서 exception은 무시됨
### 그럼 대체 이거의 용도는?
- 안전망 역할 : 혹시, close를 호출 하지 않을 것에 대한 안전망
- 네이티브 객체 회수 (garbage collector가 못함)  native 에제 - [Java Tip 23: Write native methods | JavaWorld](https://www.javaworld.com/article/2077520/learn-java/java-tip-23--write-native-methods.html)    <= ***
### 대안?
- AutoCloseable implement , close() method implement 
- 하지만 그냥 안전망 역할
