### ISSUE TITLE
아이템 80. 스레드보다는 실행자, 태스크, 스트림을 애용하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#80]

**Comment by duckcalf** [comment]
### 실행자 프레임워크 사용하기
- 초판에서는 작업 큐를 사용하는 방법을 소개 했으나, 매우 복잡한 코드가 들어갔음
- 하지만 지금은 아래와 같이 간단하게 실행자 프레임워크를 사용할 수 있음
```Java
// 큐 생성
ExecutorService exec = Executors.newSingleThreadExecutor();

// 태스크 실행
exec.execute(runnable);

// 실행자 종료
exec.shutdown();
```

### 실행자 프레임워크의 장점
- 특정 태스크가 완료되기를 기다릴 수 있다. (submit().get())
```Java
Future<Integer> f = exe.submit(task);
System.out.println("before");
f.get();   // 끝날때 까지 기다림 
System.out.println("after");
```
- 태스크 모음 중 아무거나 하나(invokeAny) 혹은 모든 태스크(invokeAll)가 완료되길 기다릴 수 있다.
```Java
List<Future<Integer>> futureList = exe.invokeAll(tasks);
System.out.println("All done");
exe.invokeAny(tasks);
System.out.println("Something done");
```
- 실행자 서비스가 종료하기를 기다릴 수 있다. (awaitTermination)
```Java
Future<Integer> f = exe.submit(task);
System.out.println("before");
exe.awaitTermination(10, TimeUnit.SECONDS);
System.out.println("after");
```
- 완료된 태스크들의 결과를 차례로 받을 수 있다. (ExecutorCompletionService)
- 태스크를 특정 시간에 혹은 주기적으로 실행하게 할 수 있다. (ScheduledThreadPoolExecutor)


### ThreadPool 종류
- 가벼운 프로그램을 돌리는 서버라면 Executors.newCachedThreadPool을 이용
   - 요청받은 태스크를 큐에 쌓지 않고 바로 처리함
   - 가용한 스레드가 없다면, 즉시 스레드를 새로 생성하여 처리
   - 무거운 태스크가 있거나, 계속 요청이 쌓인다면 문제가 될 수 있음
- 무거운 프로덕션에서는 Executors.newFixedThreadPool 을 이용
- 필요하다면  ThreadPoolExecutor를 직접 사용하는 방법도 있지만, 비추!


### 멀티태스킹 다루기
- 작업큐를 직접 만들거나, Thread를 직접 다루는것은 삼가 한다.
- 실행자 프레임워크를 이용하면, 작업 단위와 실행 매커니즘을 분리할 수 있다.
- 작업 단위는 Runnable와 Callable로 나눌 수 있다. (Callable은 Runnable과 비슷하지만, 값을 반환하고 임의의 예외를 던질 수 있다.)
- 자바7부터 ForkJoinPool이라는 특별한 실행자 서비스가 있다.
   - ForkJoinTask의 인스턴스는 작은 하위 태스크로 나눌 수 있다.
   - 일을 먼저 끝낸 스레드른 다른 스레드의 남은 태스크를 가져와서 대신 처리할 수 있다.
   - 최대한 CPU의 사용을 뽑아냄으로 효율적으로 사용할 수 있다.
   - 병렬 스트림(아이템 #48)이 이러한 ForkJoinPool을 이용해서 구현되어 있다.
