### ISSUE TITLE
아이템 83. 지연 초기화는 신중히 사용하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#83]

**Comment by gaepury** [comment]
### 필요할때까지는 하지말라. 지연 초기화는 양날의 검이다.
- 최적화와 마찬가지(#67)
- 초기화가 이뤄지는 비율에 따라, 초기화에 드는 비용에 따라, 초기화된 각 필드를 얼마나 빈번히 호출하느냐에 따라 지연초기화가 성능을 느려지게 할 수도 있다.
   - #3 : 싱글톤 지연 초기화 방법 소개 했던 Item(CL(checing lock), DCL(double checking lock), lazy holder 기법)

#### 인스턴스 필드의 지연 초기화 - synchronized 접근자 방식(CL)
- 정적 필드에도 똑같이 적용됨
- synchronized를 사용한 동기화. 메서드를 동기화시키면 성능 악화
```
    private FieldType field2;
    private synchronized FieldType getField2() {
        if (field2 == null)
            field2 = computeFieldValue();
        return field2;
    }
```

#### 인스턴스 필드 지연 초기화용 이중검사 관용구 - synchronized 접근자 방식(DCL)
- CL의 성능 문제를 개선해준다.
- 변수가 초기화된 이후로는 동기화 하지 않기 때문에 volatile 사용
- result를 지역변수로 사용하면 성능상 1.4배가 빠르다.
```
    private volatile FieldType field4;

    private FieldType getField4() {
        FieldType result = field4;
        if (result != null)    // First check (no locking)
            return result;

        synchronized(this) {
            if (field4 == null) // Second check (with locking)
                field4 = computeFieldValue();
            return field4;
        }
    }
```
#### 인스턴스 필드 지연 초기화용 단일검사 관용구 - 이중검사 관용구의 변종
- 반복해서 초기화 해도 상관없는 경우 second check 를 제외
- FieldType이 기본타입(long, double제외)라면 volatile 생략 가능
```
     private volatile FieldType field5;

    private FieldType getField5() {
        FieldType result = field5;
        if (result == null)
            field5 = result = computeFieldValue();
        return result;
    }
```

#### 정적 필드용 지연 초기화 홀더 클래스 관용구
- 성능 때문에 정적 필드를 초기화해야 한다면 지연초기화 홀더 클래스 관용구를 사용하자
```
    private static class FieldHolder {
        static final FieldType field = computeFieldValue();
    }

    private static FieldType getField() { return FieldHolder.field; }
```


### 결론
- 지연 초기화를 최대한 사용하지 말자
- 꼭 지연 초기화를 써야 한다면 인스턴스 필드에는 이중검사 관용구를, 정적 필드에는 지연 초기화 홀더 클래스 관용구를 사용하자. 반복해 초기화해도 괜찮은 인스턴스 필드에는 단일검사 관용구도 고려 대상이다

**Comment by gaepury** [comment]
#
