### ISSUE TITLE
아이템 84. 프로그램의 동작을 스레드 스케줄러에 기대지 말라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#84]

**Comment by nypark425** [comment]
### 스레드 스케줄러에 의존하지 말라.
- 스레드 스케줄러의 정책은 OS마다 다릅니다.
- 그러므로 작성한 프로그램은 스케줄러의 동작 방식에 의존하면 안되며,
의존하게 되면 스레드 스케줄러마다 성능이 달라질 수 있으므로 다른 플랫폼에 이식하기 어려워집니다.

### 성능과 이식성이 좋은 프로그램을 만들려면?
- 실행 가능한(RUNNABLE) 스레드의 평균적인 수 >>>> 프로세스 수 (X)
    - 스레드 스케줄러의 고민을 덜어줄 수 있도록 지나치게 많지 않게!
- 실행 준비가 된 스레드들은 맡은 작업을 완료할 때 까지 계속 실행되도록 만듭시다.
- 실행 가능한 스레드 수를 적게 유지하려면?
    - 각 스레드가 작업을 완료한 후 다음 작업이 생길 때 까지 대기(WAITING)하도록 하는 것
- **스레드는 당장 처리해야할 작업이 없다면 실행되어서는 안됩니다.**
    - 실행자 프레임워크(#80)을 예로 든다면, 스레드 풀 크기를 적절히 설정하고 작업은 짧게 유지하면 됨!
        - 오히려 너무 짧으면 성능은 저하

### 스레드는 절대 바쁜 대기(BUSY WAITING) 상태가 되면 안된다.
- 공유 객체의 상태를 쉬지 않고 검사해서는 안된다는 뜻
- BUSY WAITING은...
    - 스레드 스케줄러의 변덕에 취약
    - 프로세서에 큰 부담을 주어 다른 유용한 작업이 실행될 기회를 박탈
```java
public class SlowCountDownLatch {
    private int count;
    
    public SlowCountDownLatch(int count) {
        if (count < 0)
            throw new IllegalArgumentException(count + " < 0");
        this.count = count;
    }
    
    public void await() {
        while (true) {
            synchronized (this) {
                if (count == 0) // 상태를 계속 검사 
                    return;
            }
        }
    }
    
    public synchronized void countDown() {
        if (count != 0) {
            count--;
        }
    }
}
```
- java의 ```java.util.concurrent.CountDownLatch```보다 성능이 10배나 느림
- 하나 이상의 스레드가 필요도 없이 실행 가능한 상태인 시스템은 성능과 이식성이 저하됨

### ```Thread.yield```를 써서 고치려는 유혹은 떨쳐내자.
- ```Thread.yield``` : 동작을 하지 않는 스레드가 WAITING 상태가 되는 등 다른 스레드에게 실행을 양보(yield)하는 것
- 하지만 스레드 문제 해결을 yield로 하지는 맙시다.
    - 테스트할 수단도 없음
    - 애플리케이션 구조 개선을 통해 동시에 실행 가능한 스레드 수가 적어지도록 조치
- 비슷한 의미로, 스레드 우선순위를 조정하는 것도 지양합시다.
    - 스레드 우선순위는 자바에서 이식성이 가장 나쁜 특성에 속합니다.
- 진짜 문제를 찾아서 해결하지 않는 한 위 문제들은 반복적으로 계속 나타날 것입니다.
