### ISSUE TITLE
아이템 86. SERIALIZABLE을 구현할지는 신중히 결정하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#86]

**Comment by fairsun** [comment]
## implements Serializable
- 어떤 클래스의 인스턴트를 직렬화할 수 있게 하려면 클래스에 선언 추가
- 쉽게 추가할 수 있지만 직렬과 지원은 아주 값비싼 일.

## Serializable을 구현하며 릴리스하는 뒤에는 수정하기 어렵다.
- 작렬하더니 바이트 스트림 인코딩(직렬화 형태)도 하나의 API가 된다.
- 기본 직렬화 형태에서는 클래스의 private 과 package-private 인스턴트 필드들마저 API 로 공개된다. (캡슐화 깨짐)
- 필드로의 접근을 최대한 막아 정보를 은닉하라는 조언(#15)도 무력화된다.
- 직렬화 가능 클래스를 만들고자 한다면 고품질의 직렬화 형태를 주의해서 설계해야 한다.(#87 , #90 )
- 직렬버전 UID  
    - 모든 직렬화된 클래스의 고유 식별 번호를 부여 받는다.
    - static final log serialVersionUID 
    - 명시하지 않으면 시스템이 런타임에 암호 해시 함수(SHA-1)을 적용해 자동으로 클래스 안에 생성해 넣는다.
    - 클래스 이름, 구현한 인터페이스를, 컴파일러가 자동으로 생성해 넣은 것을 포함한 대부분의 클래스 멤버들은 고려해서 값을 부여한다.
    - 추후 메세지를 추가하면 UID 값이 변해서 런타임에 InvalidClassException 이 발생한다.

## 버그와 보안 구멍이 생길 위험이 높아진다.(#85)
- 직렬화는 언어의 기본 메커니즘을 우회하는 객체 생성 기법이다.
- 역직렬화는 일반 생성하는 문제가 그래도 적용되는 ‘숨은 생성자’다.
- #88 : 역직렬화를 사용하면 불변시켜 깨짐과 허가되지 않은 접근에 쉽게 노출된다.

## 해당 클래스의 신버전을 릴리스할 때 테스트할 것이 늘어난다.
- 직렬화 가능 클래스가 수정되면 신버전 인스턴트를 직렬화한 후 구버전으로 역직렬화할 수 있는지, 그리고 그 반대도 가능한지를 테스트해야한다. 
- #87 , #90 

## 구현 여부는 가볍게 결정할 사안이 아니다.
- BigInteger와 Instant 같은 ‘값’ 클래스의 컬렉션 클래스들은 Serializable을 구현하고, 스레드 풀처럼 ‘동작’하는 객체를 표현하는 클래스들은 대부분 Serializable을 구현하지 않는다.

## 상속용으로 설계된 클래스(#19)는 대부분 Serializable을 구현하며 안 되며, 인터페이스도 대부분 Serializable을 확장해서는 안 된다.
- Throwable : 서버가 RMI 를 통해 클라이언트로 예외를 보내기 위해 Serializable을 구현함.
- Component : GUI를 전송하고 저장하고 복원하기 위해 Serializable을 구현함.
-  직렬화와 확장이 모두 가능한 클래스의 경우
    - 인스턴트 필드 값 중 불변성을 보장해야 할 게 있다면 반드시 하위 클래스에서 finalize 메서드를 재정이 하지 못하게 해야 한다.(#8)
    - 인스턴트 필드 중 기반값으로 초기화되면 위배되는 불변시키어 있다면 클래스에 readObjectNoData메서드를 반드시 추가한다.
    - 상태가 있고 확장 가능하고 직렬화 가능한 클래스의 readObjectNoData 메서드
~~~java
private void readObjectNoData() throws InvalidObjectException {
    throw new InvalidObjectException(“스트림 데이터가 필요합니다”);
}
~~~

## 내부 클래스(#24)는 직렬화를 구현하지 말아야 한다.
- 내부 클래스에서는 바깥 인스턴트의 참조와 유효 범위 안의 지역본부 값을 저장하기 위해 컴파일러가 생성한 필드들이 자동으로 추가된다.
- 내부 클래스에 대한 기본 직렬화 형태는 분명하지 않다.
- 단, 정적 멤버 클래스의 Serializable을 구현해도 된다.
