### ISSUE TITLE
아이템 89. 인스턴스 수를 통제해야 한다면 READRESOLVE보다는 열거 타입을 사용하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#89]

**Comment by duckcalf** [comment]
아이템 #3에서 다음과 같은 싱글턴 패턴을 보여주었다.
```Java
public class Elvis {
   public static final Elvis INSTANCE = new Elvis();
   private Elvis() { ... }
}
```
- 하지만, implements Serializable이 되는순간 싱글턴이 아니게 된다.
- 기본 직렬화를 써도 소용 없고(아이템 #87), 명시적인 readObject를 제공해도 소용 없다.(아이템 #88)
- readResolve기능을 이용하면 readObject가 만들어낸 인스턴스를 다른것으로 대체할 수 있다. 이때 readObject가 만들어낸 인스턴스는 gc대상이 된다.
```Java
private Object readResolve() {
   return INSTANCE;
}
```
- readResolve를 인스턴스 통제 목적으로 이용한다면, 모든 필드를 transient로 선언해야 한다.
   - transient로 선언하면, Deserialize를 할때 데이터가 들어가지 않음
- 만약 transient로 선언하지 않는다면, Deserialize를 할때 그 Desieialize된 인스턴스를 가져올 수 있다. (이러면 싱글턴이 깨진다)
- 이런거 다 필요없고, 그냥 enum으로 만들면 해결 된다.
```Java
public enum Elvis {
   INSTNACE;
   private ... // 각종 필요한 데이터들
}
```
- 하지만, reflection을 쓰면 어차피 다 뚫림 ;;
